/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BibleVersePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultTranslation: "eng_kjv",
  preferredWebsite: "BibleGateway",
  displayStyle: "callout",
  persistVerseText: false,
  sidebarTopPadding: 0.5,
  showVerseNumbers: true,
  verseNewLine: false,
  bakeInline: false
};

// src/constants.ts
var USFM_CODES = {
  "Genesis": "GEN",
  "Exodus": "EXO",
  "Leviticus": "LEV",
  "Numbers": "NUM",
  "Deuteronomy": "DEU",
  "Joshua": "JOS",
  "Judges": "JDG",
  "Ruth": "RUT",
  "1 Samuel": "1SA",
  "2 Samuel": "2SA",
  "1 Kings": "1KI",
  "2 Kings": "2KI",
  "1 Chronicles": "1CH",
  "2 Chronicles": "2CH",
  "Ezra": "EZR",
  "Nehemiah": "NEH",
  "Esther": "EST",
  "Job": "JOB",
  "Psalms": "PSA",
  "Proverbs": "PRO",
  "Ecclesiastes": "ECC",
  "Song of Solomon": "SNG",
  "Isaiah": "ISA",
  "Jeremiah": "JER",
  "Lamentations": "LAM",
  "Ezekiel": "EZK",
  "Daniel": "DAN",
  "Hosea": "HOS",
  "Joel": "JOL",
  "Amos": "AMO",
  "Obadiah": "OBA",
  "Jonah": "JON",
  "Micah": "MIC",
  "Nahum": "NAM",
  "Habakkuk": "HAB",
  "Zephaniah": "ZEP",
  "Haggai": "HAG",
  "Zechariah": "ZEC",
  "Malachi": "MAL",
  "Matthew": "MAT",
  "Mark": "MRK",
  "Luke": "LUK",
  "John": "JHN",
  "Acts": "ACT",
  "Romans": "ROM",
  "1 Corinthians": "1CO",
  "2 Corinthians": "2CO",
  "Galatians": "GAL",
  "Ephesians": "EPH",
  "Philippians": "PHP",
  "Colossians": "COL",
  "1 Thessalonians": "1TH",
  "2 Thessalonians": "2TH",
  "1 Timothy": "1TI",
  "2 Timothy": "2TI",
  "Titus": "TIT",
  "Philemon": "PHM",
  "Hebrews": "HEB",
  "James": "JAS",
  "1 Peter": "1PE",
  "2 Peter": "2PE",
  "1 John": "1JN",
  "2 John": "2JN",
  "3 John": "3JN",
  "Jude": "JUD",
  "Revelation": "REV"
};
var BLB_CODES = {
  "Genesis": "gen",
  "Exodus": "exo",
  "Leviticus": "lev",
  "Numbers": "num",
  "Deuteronomy": "deu",
  "Joshua": "jos",
  "Judges": "jdg",
  "Ruth": "rut",
  "1 Samuel": "1sa",
  "2 Samuel": "2sa",
  "1 Kings": "1ki",
  "2 Kings": "2ki",
  "1 Chronicles": "1ch",
  "2 Chronicles": "2ch",
  "Ezra": "ezr",
  "Nehemiah": "neh",
  "Esther": "est",
  "Job": "job",
  "Psalms": "psa",
  "Proverbs": "pro",
  "Ecclesiastes": "ecc",
  "Song of Solomon": "sng",
  "Isaiah": "isa",
  "Jeremiah": "jer",
  "Lamentations": "lam",
  "Ezekiel": "eze",
  "Daniel": "dan",
  "Hosea": "hos",
  "Joel": "joe",
  "Amos": "amo",
  "Obadiah": "oba",
  "Jonah": "jon",
  "Micah": "mic",
  "Nahum": "nah",
  "Habakkuk": "hab",
  "Zephaniah": "zep",
  "Haggai": "hag",
  "Zechariah": "zec",
  "Malachi": "mal",
  "Matthew": "mat",
  "Mark": "mar",
  "Luke": "luk",
  "John": "jhn",
  "Acts": "act",
  "Romans": "rom",
  "1 Corinthians": "1co",
  "2 Corinthians": "2co",
  "Galatians": "gal",
  "Ephesians": "eph",
  "Philippians": "php",
  "Colossians": "col",
  "1 Thessalonians": "1th",
  "2 Thessalonians": "2th",
  "1 Timothy": "1ti",
  "2 Timothy": "2ti",
  "Titus": "tit",
  "Philemon": "phm",
  "Hebrews": "heb",
  "James": "jas",
  "1 Peter": "1pe",
  "2 Peter": "2pe",
  "1 John": "1jn",
  "2 John": "2jn",
  "3 John": "3jn",
  "Jude": "jud",
  "Revelation": "rev"
};
var BIBLEHUB_SLUGS = {
  "Genesis": "genesis",
  "Exodus": "exodus",
  "Leviticus": "leviticus",
  "Numbers": "numbers",
  "Deuteronomy": "deuteronomy",
  "Joshua": "joshua",
  "Judges": "judges",
  "Ruth": "ruth",
  "1 Samuel": "1_samuel",
  "2 Samuel": "2_samuel",
  "1 Kings": "1_kings",
  "2 Kings": "2_kings",
  "1 Chronicles": "1_chronicles",
  "2 Chronicles": "2_chronicles",
  "Ezra": "ezra",
  "Nehemiah": "nehemiah",
  "Esther": "esther",
  "Job": "job",
  "Psalms": "psalms",
  "Proverbs": "proverbs",
  "Ecclesiastes": "ecclesiastes",
  "Song of Solomon": "songs",
  "Isaiah": "isaiah",
  "Jeremiah": "jeremiah",
  "Lamentations": "lamentations",
  "Ezekiel": "ezekiel",
  "Daniel": "daniel",
  "Hosea": "hosea",
  "Joel": "joel",
  "Amos": "amos",
  "Obadiah": "obadiah",
  "Jonah": "jonah",
  "Micah": "micah",
  "Nahum": "nahum",
  "Habakkuk": "habakkuk",
  "Zephaniah": "zephaniah",
  "Haggai": "haggai",
  "Zechariah": "zechariah",
  "Malachi": "malachi",
  "Matthew": "matthew",
  "Mark": "mark",
  "Luke": "luke",
  "John": "john",
  "Acts": "acts",
  "Romans": "romans",
  "1 Corinthians": "1_corinthians",
  "2 Corinthians": "2_corinthians",
  "Galatians": "galatians",
  "Ephesians": "ephesians",
  "Philippians": "philippians",
  "Colossians": "colossians",
  "1 Thessalonians": "1_thessalonians",
  "2 Thessalonians": "2_thessalonians",
  "1 Timothy": "1_timothy",
  "2 Timothy": "2_timothy",
  "Titus": "titus",
  "Philemon": "philemon",
  "Hebrews": "hebrews",
  "James": "james",
  "1 Peter": "1_peter",
  "2 Peter": "2_peter",
  "1 John": "1_john",
  "2 John": "2_john",
  "3 John": "3_john",
  "Jude": "jude",
  "Revelation": "revelation"
};
var BIBLE_COM_TRANSLATION_IDS = {
  "KJV": 1,
  "ESV": 59,
  "NASB": 100,
  "NIV": 111,
  "NKJV": 114,
  "NLT": 116,
  "AMP": 1588,
  "CSB": 1713,
  "MSG": 97,
  "RSV": 2020
};
var HELLOAO_TRANSLATIONS = [
  { id: "eng_kjv", name: "King James Version (KJV)", abbreviation: "KJV" },
  { id: "BSB", name: "Berean Standard Bible (BSB)", abbreviation: "BSB" },
  { id: "eng_asv", name: "American Standard Version (ASV)", abbreviation: "ASV" },
  { id: "eng_web", name: "World English Bible (WEB)", abbreviation: "WEB" },
  { id: "eng_net", name: "NET Bible (NET)", abbreviation: "NET" },
  { id: "eng_dby", name: "Darby Translation (DARBY)", abbreviation: "DARBY" },
  { id: "eng_dra", name: "Douay-Rheims 1899 (DRB)", abbreviation: "DRB" },
  { id: "eng_rv5", name: "Revised Version (ERV)", abbreviation: "ERV" },
  { id: "eng_kja", name: "King James + Apocrypha (KJV+)", abbreviation: "KJV+" },
  { id: "eng_wbs", name: "Webster Bible (WBT)", abbreviation: "WBT" },
  { id: "eng_ylt", name: "Young's Literal Translation (YLT)", abbreviation: "YLT" },
  { id: "eng_bbe", name: "Bible in Basic English (BBE)", abbreviation: "BBE" },
  { id: "eng_fbv", name: "Free Bible Version (FBV)", abbreviation: "FBV" },
  { id: "eng_lsv", name: "Literal Standard Version (LSV)", abbreviation: "LSV" },
  { id: "eng_msb", name: "Majority Standard Bible (MSB)", abbreviation: "MSB" },
  { id: "ENGWEBP", name: "World English Bible (WEB-P)", abbreviation: "WEBP" },
  { id: "eng_gnv", name: "Geneva Bible 1599 (GNV)", abbreviation: "GNV" },
  { id: "eng_ojb", name: "Orthodox Jewish Bible (OJB)", abbreviation: "OJB" }
];
var HELLOAO_ABBREV = Object.fromEntries(
  HELLOAO_TRANSLATIONS.map((t) => [t.id, t.abbreviation])
);
var BOOK_ALIASES = {
  // Psalm vs Psalms
  "psalm": "Psalms",
  "psalms": "Psalms",
  "ps": "Psalms",
  "psa": "Psalms",
  // Song of Solomon variations
  "song of solomon": "Song of Solomon",
  "song of songs": "Song of Solomon",
  "songs": "Song of Solomon",
  "sos": "Song of Solomon",
  "sng": "Song of Solomon",
  "song": "Song of Solomon",
  // Genesis
  "genesis": "Genesis",
  "gen": "Genesis",
  // Exodus
  "exodus": "Exodus",
  "exod": "Exodus",
  "exo": "Exodus",
  "ex": "Exodus",
  // Leviticus
  "leviticus": "Leviticus",
  "lev": "Leviticus",
  // Numbers
  "numbers": "Numbers",
  "num": "Numbers",
  // Deuteronomy
  "deuteronomy": "Deuteronomy",
  "deut": "Deuteronomy",
  "deu": "Deuteronomy",
  "dt": "Deuteronomy",
  // Joshua
  "joshua": "Joshua",
  "josh": "Joshua",
  "jos": "Joshua",
  // Judges
  "judges": "Judges",
  "judg": "Judges",
  "jdg": "Judges",
  // Ruth
  "ruth": "Ruth",
  "rut": "Ruth",
  // Samuel
  "1 samuel": "1 Samuel",
  "1samuel": "1 Samuel",
  "1 sam": "1 Samuel",
  "1sam": "1 Samuel",
  "1sa": "1 Samuel",
  "2 samuel": "2 Samuel",
  "2samuel": "2 Samuel",
  "2 sam": "2 Samuel",
  "2sam": "2 Samuel",
  "2sa": "2 Samuel",
  // Kings
  "1 kings": "1 Kings",
  "1kings": "1 Kings",
  "1 kgs": "1 Kings",
  "1kgs": "1 Kings",
  "1ki": "1 Kings",
  "2 kings": "2 Kings",
  "2kings": "2 Kings",
  "2 kgs": "2 Kings",
  "2kgs": "2 Kings",
  "2ki": "2 Kings",
  // Chronicles
  "1 chronicles": "1 Chronicles",
  "1chronicles": "1 Chronicles",
  "1 chr": "1 Chronicles",
  "1chr": "1 Chronicles",
  "1ch": "1 Chronicles",
  "2 chronicles": "2 Chronicles",
  "2chronicles": "2 Chronicles",
  "2 chr": "2 Chronicles",
  "2chr": "2 Chronicles",
  "2ch": "2 Chronicles",
  // Ezra
  "ezra": "Ezra",
  "ezr": "Ezra",
  // Nehemiah
  "nehemiah": "Nehemiah",
  "neh": "Nehemiah",
  // Esther
  "esther": "Esther",
  "est": "Esther",
  // Job
  "job": "Job",
  // Proverbs
  "proverbs": "Proverbs",
  "prov": "Proverbs",
  "pro": "Proverbs",
  "pr": "Proverbs",
  // Ecclesiastes
  "ecclesiastes": "Ecclesiastes",
  "eccl": "Ecclesiastes",
  "ecc": "Ecclesiastes",
  "eccles": "Ecclesiastes",
  // Isaiah
  "isaiah": "Isaiah",
  "isa": "Isaiah",
  "is": "Isaiah",
  // Jeremiah
  "jeremiah": "Jeremiah",
  "jer": "Jeremiah",
  // Lamentations
  "lamentations": "Lamentations",
  "lam": "Lamentations",
  // Ezekiel
  "ezekiel": "Ezekiel",
  "ezek": "Ezekiel",
  "eze": "Ezekiel",
  "ezk": "Ezekiel",
  // Daniel
  "daniel": "Daniel",
  "dan": "Daniel",
  // Hosea
  "hosea": "Hosea",
  "hos": "Hosea",
  // Joel
  "joel": "Joel",
  "joe": "Joel",
  // Amos
  "amos": "Amos",
  // Obadiah
  "obadiah": "Obadiah",
  "oba": "Obadiah",
  "obad": "Obadiah",
  // Jonah
  "jonah": "Jonah",
  "jon": "Jonah",
  // Micah
  "micah": "Micah",
  "mic": "Micah",
  // Nahum
  "nahum": "Nahum",
  "nah": "Nahum",
  "nam": "Nahum",
  // Habakkuk
  "habakkuk": "Habakkuk",
  "hab": "Habakkuk",
  // Zephaniah
  "zephaniah": "Zephaniah",
  "zeph": "Zephaniah",
  "zep": "Zephaniah",
  // Haggai
  "haggai": "Haggai",
  "hag": "Haggai",
  // Zechariah
  "zechariah": "Zechariah",
  "zech": "Zechariah",
  "zec": "Zechariah",
  // Malachi
  "malachi": "Malachi",
  "mal": "Malachi",
  // Matthew
  "matthew": "Matthew",
  "matt": "Matthew",
  "mat": "Matthew",
  "mt": "Matthew",
  // Mark
  "mark": "Mark",
  "mrk": "Mark",
  "mk": "Mark",
  // Luke
  "luke": "Luke",
  "luk": "Luke",
  "lk": "Luke",
  // John (not 1/2/3 John)
  "john": "John",
  "jhn": "John",
  "jn": "John",
  // Acts
  "acts": "Acts",
  "act": "Acts",
  // Romans
  "romans": "Romans",
  "rom": "Romans",
  "ro": "Romans",
  // Corinthians
  "1 corinthians": "1 Corinthians",
  "1corinthians": "1 Corinthians",
  "1 cor": "1 Corinthians",
  "1cor": "1 Corinthians",
  "1co": "1 Corinthians",
  "2 corinthians": "2 Corinthians",
  "2corinthians": "2 Corinthians",
  "2 cor": "2 Corinthians",
  "2cor": "2 Corinthians",
  "2co": "2 Corinthians",
  // Galatians
  "galatians": "Galatians",
  "gal": "Galatians",
  // Ephesians
  "ephesians": "Ephesians",
  "eph": "Ephesians",
  // Philippians
  "philippians": "Philippians",
  "phil": "Philippians",
  "php": "Philippians",
  // Colossians
  "colossians": "Colossians",
  "col": "Colossians",
  // Thessalonians
  "1 thessalonians": "1 Thessalonians",
  "1thessalonians": "1 Thessalonians",
  "1 thess": "1 Thessalonians",
  "1thess": "1 Thessalonians",
  "1th": "1 Thessalonians",
  "2 thessalonians": "2 Thessalonians",
  "2thessalonians": "2 Thessalonians",
  "2 thess": "2 Thessalonians",
  "2thess": "2 Thessalonians",
  "2th": "2 Thessalonians",
  // Timothy
  "1 timothy": "1 Timothy",
  "1timothy": "1 Timothy",
  "1 tim": "1 Timothy",
  "1tim": "1 Timothy",
  "1ti": "1 Timothy",
  "2 timothy": "2 Timothy",
  "2timothy": "2 Timothy",
  "2 tim": "2 Timothy",
  "2tim": "2 Timothy",
  "2ti": "2 Timothy",
  // Titus
  "titus": "Titus",
  "tit": "Titus",
  // Philemon
  "philemon": "Philemon",
  "phm": "Philemon",
  "phlm": "Philemon",
  // Hebrews
  "hebrews": "Hebrews",
  "heb": "Hebrews",
  // James
  "james": "James",
  "jas": "James",
  // Peter
  "1 peter": "1 Peter",
  "1peter": "1 Peter",
  "1 pet": "1 Peter",
  "1pet": "1 Peter",
  "1pe": "1 Peter",
  "2 peter": "2 Peter",
  "2peter": "2 Peter",
  "2 pet": "2 Peter",
  "2pet": "2 Peter",
  "2pe": "2 Peter",
  // John epistles
  "1 john": "1 John",
  "1john": "1 John",
  "1 jn": "1 John",
  "1jn": "1 John",
  "2 john": "2 John",
  "2john": "2 John",
  "2 jn": "2 John",
  "2jn": "2 John",
  "3 john": "3 John",
  "3john": "3 John",
  "3 jn": "3 John",
  "3jn": "3 John",
  // Jude
  "jude": "Jude",
  "jud": "Jude",
  // Revelation
  "revelation": "Revelation",
  "rev": "Revelation",
  "re": "Revelation"
};

// src/parser.ts
var REF_REGEX = /^(\d?\s?[A-Za-z]+(?:\s+(?:of\s+)?[A-Za-z]+)*)\s+(\d+)(?::(\d+)(?:-(\d+):(\d+)|-(eoc|\d+|-))?((?:,\s*\d+)*))?$/i;
function normalizeBookName(raw) {
  var _a;
  const key = raw.trim().toLowerCase();
  return (_a = BOOK_ALIASES[key]) != null ? _a : null;
}
function parseReference(input) {
  const trimmed = input.trim();
  const match = trimmed.match(REF_REGEX);
  if (!match)
    return null;
  const rawBook = match[1];
  const chapter = parseInt(match[2], 10);
  const book = normalizeBookName(rawBook);
  if (!book)
    return null;
  if (match[3] === void 0) {
    return {
      book,
      chapter,
      startVerse: null,
      endVerse: null,
      additionalVerses: [],
      endChapter: null,
      raw: trimmed
    };
  }
  const startVerse = parseInt(match[3], 10);
  if (match[4] !== void 0 && match[5] !== void 0) {
    const endChapter = parseInt(match[4], 10);
    const endVerse2 = parseInt(match[5], 10);
    return {
      book,
      chapter,
      startVerse,
      endVerse: endVerse2,
      additionalVerses: [],
      endChapter,
      raw: trimmed
    };
  }
  let endVerse = null;
  if (match[6] !== void 0) {
    const val = match[6].toLowerCase();
    if (val === "eoc" || val === "-") {
      endVerse = 999;
    } else {
      endVerse = parseInt(val, 10);
    }
  }
  const additionalVerses = [];
  if (match[7]) {
    const parts = match[7].split(",").filter((s) => s.trim().length > 0);
    for (const part of parts) {
      const v = parseInt(part.trim(), 10);
      if (!isNaN(v))
        additionalVerses.push(v);
    }
  }
  return {
    book,
    chapter,
    startVerse,
    endVerse,
    additionalVerses,
    endChapter: null,
    raw: trimmed
  };
}
var TRANS_CODE_RE = /^[A-Za-z][A-Za-z0-9_]*$/;
var KNOWN_STYLES = [
  "sidebar",
  "callout",
  "blockquote",
  "inline"
];
function isKnownStyle(token) {
  return KNOWN_STYLES.includes(token.toLowerCase());
}
function parseInlineSpec(content) {
  const trimmed = content.trim();
  const simpleRef = parseReference(trimmed);
  if (simpleRef) {
    return { ref: simpleRef, translations: [], styleOverride: null };
  }
  const parts = trimmed.split(",").map((p) => p.trim());
  if (parts.length < 2)
    return null;
  const translations = [];
  let styleOverride = null;
  let cut = parts.length;
  while (cut > 1) {
    const tok = parts[cut - 1];
    if (isKnownStyle(tok)) {
      if (styleOverride !== null)
        break;
      styleOverride = tok.toLowerCase();
      cut--;
      continue;
    }
    if (TRANS_CODE_RE.test(tok)) {
      if (translations.length >= 2)
        break;
      translations.unshift(tok.toUpperCase());
      cut--;
      continue;
    }
    break;
  }
  if (cut === parts.length)
    return null;
  const refStr = parts.slice(0, cut).join(",");
  const ref = parseReference(refStr);
  if (!ref)
    return null;
  return { ref, translations, styleOverride };
}
function formatReference(ref) {
  let s = `${ref.book} ${ref.chapter}`;
  if (ref.startVerse !== null) {
    s += `:${ref.startVerse}`;
    if (ref.endChapter !== null && ref.endVerse !== null) {
      s += `-${ref.endChapter}:${ref.endVerse}`;
    } else if (ref.endVerse !== null) {
      s += `-${ref.endVerse}`;
    }
    if (ref.additionalVerses.length > 0) {
      s += "," + ref.additionalVerses.join(",");
    }
  }
  return s;
}

// src/api.ts
var import_obsidian = require("obsidian");
var BASE_URL = "https://bible.helloao.org/api";
var BibleApi = class {
  constructor(cache) {
    this.cache = cache;
  }
  /**
   * Extract text from a HelloAO verse content array.
   * Content items can be plain strings or objects with a `text` property
   * (e.g. wordsOfJesus markers, footnotes). We extract only text content.
   */
  extractVerseText(content) {
    const parts = [];
    for (const item of content) {
      if (typeof item === "string") {
        parts.push(item);
      } else if (typeof item === "object" && item !== null) {
        const obj = item;
        if ("text" in obj) {
          let text = obj.text;
          if (obj.poem) {
            const indent = "\xA0".repeat(Number(obj.poem) * 2);
            const prefix = parts.length > 0 ? "\n" : "";
            text = prefix + indent + text;
          }
          parts.push(text);
        } else if (obj.lineBreak || obj.type === "line_break") {
          parts.push("\n");
        }
      }
    }
    return parts.join(" ").replace(/\s?\n\s?/g, "\n").trim();
  }
  /**
   * Determine which verses from the chapter are needed for this reference.
   * Returns a Set of verse numbers to include.
   */
  getRequestedVerses(ref) {
    if (ref.startVerse === null)
      return null;
    if (ref.endVerse === 999)
      return null;
    const verses = /* @__PURE__ */ new Set();
    if (ref.endVerse !== null && ref.endChapter === null) {
      for (let v = ref.startVerse; v <= ref.endVerse; v++) {
        verses.add(v);
      }
    } else if (ref.endVerse === null && ref.additionalVerses.length === 0) {
      verses.add(ref.startVerse);
    } else {
      if (ref.endVerse !== null) {
        for (let v = ref.startVerse; v <= ref.endVerse; v++) {
          verses.add(v);
        }
      } else {
        verses.add(ref.startVerse);
      }
      for (const v of ref.additionalVerses) {
        verses.add(v);
      }
    }
    return verses;
  }
  /**
   * Fetch a passage from HelloAO Bible API.
   * Fetches the whole chapter and extracts the requested verses client-side.
   * Returns cached version if available.
   */
  async getPassage(ref, translationId, translationAbbr, settings) {
    var _a;
    const refStr = formatReference(ref);
    const cached = this.cache.get(translationAbbr, refStr);
    if (cached)
      return cached;
    const usfm = USFM_CODES[ref.book];
    if (!usfm)
      throw new Error(`Unknown book: ${ref.book}`);
    const url = `${BASE_URL}/${translationId}/${usfm}/${ref.chapter}.json`;
    const response = await (0, import_obsidian.requestUrl)({ url });
    if (response.status !== 200) {
      throw new Error(`HelloAO API returned status ${response.status}`);
    }
    const data = response.json;
    const chapterContent = data.chapter.content;
    const requestedVerses = this.getRequestedVerses(ref);
    const verseParts = [];
    for (const item of chapterContent) {
      if (typeof item !== "object" || item === null)
        continue;
      const obj = item;
      if (obj.type === "verse") {
        const verseItem = item;
        const isIncluded = requestedVerses === null ? ref.startVerse === null || verseItem.number >= ref.startVerse : requestedVerses.has(verseItem.number);
        if (isIncluded) {
          let text2 = this.extractVerseText(verseItem.content);
          if (text2) {
            if (settings.showVerseNumbers) {
              text2 = `[${verseItem.number}] ${text2}`;
            }
            verseParts.push(text2);
          }
        }
      } else if (obj.type === "line_break" || obj.type === "paragraph" || obj.type === "stanza" || obj.type === "stanza_break") {
        verseParts.push("\n");
      }
    }
    if (verseParts.length === 0) {
      throw new Error(`No verses found for ${refStr} in ${translationAbbr}`);
    }
    const text = verseParts.join(settings.verseNewLine && settings.showVerseNumbers ? "\n" : " ").replace(/\s?\n\s?/g, "\n").replace(/\n{3,}/g, "\n\n").trim();
    const licenseUrl = (_a = data.translation) == null ? void 0 : _a.licenseUrl;
    const copyright = licenseUrl ? `License: ${licenseUrl}` : "";
    const entry = {
      reference: refStr,
      translation: translationAbbr,
      bibleId: translationId,
      text,
      copyright,
      fetchedAt: Date.now()
    };
    try {
      await this.cache.set(entry);
    } catch (e) {
      console.warn("Bible Verse: Failed to cache verse", e);
    }
    return entry;
  }
};

// src/cache.ts
var VerseCache = class {
  constructor(plugin) {
    this.cache = /* @__PURE__ */ new Map();
    this.loaded = false;
    this.plugin = plugin;
    this.cacheDir = `${plugin.manifest.dir}/cache`;
  }
  /** Build a cache key from translation and reference */
  key(translation, reference) {
    return `${translation}_${reference}`.toLowerCase().replace(/\s+/g, "_").replace(/:/g, "_");
  }
  /** Load the full cache index from disk */
  async load() {
    if (this.loaded)
      return;
    const adapter = this.plugin.app.vault.adapter;
    const exists = await adapter.exists(this.cacheDir);
    if (!exists) {
      await adapter.mkdir(this.cacheDir);
      this.loaded = true;
      return;
    }
    const files = await adapter.list(this.cacheDir);
    for (const file of files.files) {
      try {
        const data = await adapter.read(file);
        const entry = JSON.parse(data);
        const k = this.key(entry.translation, entry.reference);
        this.cache.set(k, entry);
      } catch (e) {
      }
    }
    this.loaded = true;
  }
  /** Get a cached verse, or null if not cached */
  get(translation, reference) {
    var _a;
    return (_a = this.cache.get(this.key(translation, reference))) != null ? _a : null;
  }
  /** Store a verse in the cache */
  async set(entry) {
    const k = this.key(entry.translation, entry.reference);
    this.cache.set(k, entry);
    const adapter = this.plugin.app.vault.adapter;
    const exists = await adapter.exists(this.cacheDir);
    if (!exists) {
      await adapter.mkdir(this.cacheDir);
    }
    const filePath = `${this.cacheDir}/${k}.json`;
    const parentDir = filePath.substring(0, filePath.lastIndexOf("/"));
    if (parentDir !== this.cacheDir) {
      const parentExists = await adapter.exists(parentDir);
      if (!parentExists) {
        await adapter.mkdir(parentDir);
      }
    }
    await adapter.write(filePath, JSON.stringify(entry, null, 2));
  }
  /** Check if a verse is cached */
  has(translation, reference) {
    return this.cache.has(this.key(translation, reference));
  }
  /** Clear the entire cache */
  async clear() {
    const adapter = this.plugin.app.vault.adapter;
    const exists = await adapter.exists(this.cacheDir);
    if (exists) {
      const files = await adapter.list(this.cacheDir);
      for (const file of files.files) {
        await adapter.remove(file);
      }
    }
    this.cache.clear();
  }
};

// src/baker.ts
var INLINE_REF_REGEX = /\{([A-Za-z0-9][^}\n]*)\}/g;
var CODEBLOCK_REGEX = /```bible\s*\n([\s\S]*?)\n```/g;
var CODEBLOCK_BAKE_SEPARATOR = "\n---\n";
var Baker = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Extract all bakeable references from note content.
   */
  extractReferences(content, includeInline) {
    const results = [];
    if (includeInline) {
      let match2;
      const inlineRegex = new RegExp(INLINE_REF_REGEX.source, "g");
      while ((match2 = inlineRegex.exec(content)) !== null) {
        const spec = parseInlineSpec(match2[1]);
        if (spec) {
          results.push({
            raw: match2[0],
            ref: spec.ref,
            offset: match2.index,
            type: "inline"
          });
        }
      }
    }
    let match;
    const blockRegex = new RegExp(CODEBLOCK_REGEX.source, "g");
    while ((match = blockRegex.exec(content)) !== null) {
      const body = match[1];
      const lines = body.split("\n");
      if (lines.length > 0) {
        const ref = parseReference(lines[0].trim());
        results.push({
          raw: match[0],
          ref,
          offset: match.index,
          type: "block",
          body
        });
      }
    }
    return results.sort((a, b) => a.offset - b.offset);
  }
  /**
   * Bake a verse into the content.
   * If it's an inline reference, it is CONVERTED to a code block.
   */
  bakeVerse(content, refRaw, verse, type = "inline") {
    if (type === "inline") {
      const block = `\`\`\`bible
${verse.reference}
translation: ${verse.translation}
${CODEBLOCK_BAKE_SEPARATOR}${verse.text}
\`\`\``;
      return content.replace(refRaw, block);
    } else {
      const separatorIdx = refRaw.indexOf(CODEBLOCK_BAKE_SEPARATOR);
      let newBlock;
      if (separatorIdx > 0) {
        newBlock = refRaw.substring(0, separatorIdx) + CODEBLOCK_BAKE_SEPARATOR + verse.text + "\n```";
      } else {
        newBlock = refRaw.replace(/\n```$/, CODEBLOCK_BAKE_SEPARATOR + verse.text + "\n```");
      }
      return content.replace(refRaw, newBlock);
    }
  }
  /**
   * Strip all baked text. Only affects code blocks.
   */
  stripBakedText(content) {
    return content.replace(/(```bible[\s\S]*?)\n---\n[\s\S]*?(\n```)/g, "$1$2");
  }
  /**
   * Check if a reference is already baked.
   */
  hasBakedBlock(content, refRaw, type = "inline") {
    if (type === "inline")
      return false;
    return refRaw.includes(CODEBLOCK_BAKE_SEPARATOR);
  }
  async bakeFile(content, bakeInline, fetchVerse) {
    const refs = this.extractReferences(content, bakeInline);
    if (refs.length === 0)
      return content;
    let result = content;
    for (let i = refs.length - 1; i >= 0; i--) {
      const { raw, ref, offset, type } = refs[i];
      if (!ref)
        continue;
      const verse = await fetchVerse(ref);
      if (!verse)
        continue;
      if (type === "inline") {
        const block = `\`\`\`bible
${verse.reference}
translation: ${verse.translation}
${CODEBLOCK_BAKE_SEPARATOR}${verse.text}
\`\`\``;
        result = result.slice(0, offset) + block + result.slice(offset + raw.length);
      } else {
        const separatorIdx = raw.indexOf(CODEBLOCK_BAKE_SEPARATOR);
        let newBlock;
        if (separatorIdx > 0) {
          newBlock = raw.substring(0, separatorIdx) + CODEBLOCK_BAKE_SEPARATOR + verse.text + "\n```";
        } else {
          newBlock = raw.replace(/\n```$/, CODEBLOCK_BAKE_SEPARATOR + verse.text + "\n```");
        }
        result = result.slice(0, offset) + newBlock + result.slice(offset + raw.length);
      }
    }
    return result;
  }
  async processVault(action, bakeInline, fetchVerse) {
    const files = this.app.vault.getMarkdownFiles();
    let count = 0;
    for (const file of files) {
      const content = await this.app.vault.read(file);
      let newContent;
      if (action === "strip") {
        newContent = this.stripBakedText(content);
      } else if (fetchVerse) {
        newContent = await this.bakeFile(content, bakeInline, fetchVerse);
      } else {
        continue;
      }
      if (newContent !== content) {
        await this.app.vault.modify(file, newContent);
        count++;
      }
    }
    return count;
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var BibleVerseSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Bible Verse Settings" });
    new import_obsidian2.Setting(containerEl).setName("Default Translation").setDesc("The Bible translation to use by default").addDropdown((dropdown) => {
      for (const t of HELLOAO_TRANSLATIONS) {
        dropdown.addOption(t.id, t.name);
      }
      dropdown.setValue(this.plugin.settings.defaultTranslation).onChange(async (value) => {
        this.plugin.settings.defaultTranslation = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Preferred Bible Website").setDesc("Which website to link verse references to").addDropdown(
      (dropdown) => dropdown.addOption("BibleHub", "BibleHub").addOption("BibleGateway", "BibleGateway").addOption("BlueLetter", "Blue Letter Bible").addOption("BibleCom", "Bible.com").setValue(this.plugin.settings.preferredWebsite).onChange(async (value) => {
        this.plugin.settings.preferredWebsite = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Display Style").setDesc("How verses are visually presented").addDropdown(
      (dropdown) => dropdown.addOption("sidebar", "Sidebar").addOption("callout", "Callout").addOption("blockquote", "Blockquote").addOption("inline", "Inline").setValue(this.plugin.settings.displayStyle).onChange(async (value) => {
        this.plugin.settings.displayStyle = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Sidebar Top Padding").setDesc("Adjust the top spacing for the Sidebar style (in ems)").addSlider(
      (slider) => slider.setLimits(0, 2, 0.1).setValue(this.plugin.settings.sidebarTopPadding).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.sidebarTopPadding = value;
        await this.plugin.saveSettings();
        this.plugin.updateStyles();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Persist Verse Text in Notes").setDesc(
      "When enabled, fetched verse text is automatically written into note source (bake mode)"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.persistVerseText).onChange(async (value) => {
        this.plugin.settings.persistVerseText = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Show verse numbers").setDesc("Display verse numbers in the rendered text.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showVerseNumbers).onChange(async (value) => {
        this.plugin.settings.showVerseNumbers = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("New line per verse").setDesc("Start each verse on a new line (only if verse numbers are enabled).").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.verseNewLine).setDisabled(!this.plugin.settings.showVerseNumbers).onChange(async (value) => {
        this.plugin.settings.verseNewLine = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Bake inline references").setDesc("If enabled, baking a note will convert {ref} into a bible code block. If disabled, only code blocks are baked.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.bakeInline).onChange(async (value) => {
        this.plugin.settings.bakeInline = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/linker.ts
function generateLink(ref, translation, website) {
  switch (website) {
    case "BibleHub":
      return bibleHubUrl(ref, translation);
    case "BibleGateway":
      return bibleGatewayUrl(ref, translation);
    case "BlueLetter":
      return blueLetterUrl(ref, translation);
    case "BibleCom":
      return bibleComUrl(ref, translation);
  }
}
function generateSearchUrl(query, translation, website) {
  const encoded = encodeURIComponent(query);
  switch (website) {
    case "BibleHub":
      return `https://biblehub.com/search.php?q=${encoded}`;
    case "BibleGateway":
      return `https://www.biblegateway.com/quicksearch/?search=${encoded}&version=${translation}`;
    case "BlueLetter":
      return `https://www.blueletterbible.org/search/search.cfm?Criteria=${encoded}&t=${translation.toLowerCase()}`;
    case "BibleCom":
      return `https://www.bible.com/search/bible?query=${encoded}`;
  }
}
function bibleHubUrl(ref, translation) {
  var _a;
  const slug = BIBLEHUB_SLUGS[ref.book] || ref.book.toLowerCase().replace(/\s+/g, "_");
  const trans = translation.toLowerCase();
  const verse = (_a = ref.startVerse) != null ? _a : 1;
  return `https://biblehub.com/${trans}/${slug}/${ref.chapter}-${verse}.htm`;
}
function bibleGatewayUrl(ref, translation) {
  let search = ref.book + "+" + ref.chapter;
  if (ref.startVerse !== null) {
    search += "%3A" + ref.startVerse;
    if (ref.endChapter !== null && ref.endVerse !== null) {
      search += `-${ref.endChapter}%3A${ref.endVerse}`;
    } else if (ref.endVerse !== null) {
      search += `-${ref.endVerse}`;
    }
    if (ref.additionalVerses.length > 0) {
      search += "%2C" + ref.additionalVerses.join("%2C");
    }
  }
  search = search.replace(/\s+/g, "+");
  return `https://www.biblegateway.com/passage/?search=${search}&version=${translation}`;
}
function blueLetterUrl(ref, translation) {
  var _a;
  const code = BLB_CODES[ref.book] || ref.book.substring(0, 3).toLowerCase();
  const trans = translation.toLowerCase();
  const verse = (_a = ref.startVerse) != null ? _a : 1;
  return `https://www.blueletterbible.org/${trans}/${code}/${ref.chapter}/${verse}/`;
}
function bibleComUrl(ref, translation) {
  var _a;
  const usfm = USFM_CODES[ref.book] || ref.book.substring(0, 3).toUpperCase();
  const transId = BIBLE_COM_TRANSLATION_IDS[translation.toUpperCase()] || 1;
  const verse = (_a = ref.startVerse) != null ? _a : 1;
  return `https://www.bible.com/bible/${transId}/${usfm}.${ref.chapter}.${verse}`;
}

// src/renderer.ts
function renderVerse(container, ref, verse, style, website) {
  const wrapper = container.createDiv({ cls: `bible-verse bible-verse-${style}` });
  const refStr = formatReference(ref);
  const url = generateLink(ref, verse.translation, website);
  switch (style) {
    case "sidebar":
      renderSidebar(wrapper, refStr, verse, url);
      break;
    case "callout":
      renderCallout(wrapper, refStr, verse, url);
      break;
    case "blockquote":
      renderBlockquote(wrapper, refStr, verse, url);
      break;
    case "inline":
      renderInline(wrapper, refStr, verse, url);
      break;
  }
}
function renderSidebar(el, ref, verse, url) {
  const body = el.createDiv({ cls: "bible-verse-body" });
  body.createEl("p", { cls: "bible-verse-text", text: verse.text });
  const footer = el.createDiv({ cls: "bible-verse-footer" });
  const link = footer.createEl("a", {
    cls: "bible-verse-ref",
    text: `${ref} (${verse.translation})`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
  if (verse.copyright) {
    footer.createEl("span", { cls: "bible-verse-copyright", text: verse.copyright });
  }
}
function renderCallout(el, ref, verse, url) {
  const header = el.createDiv({ cls: "bible-verse-header" });
  header.createSpan({ cls: "bible-verse-icon", text: "\u{1F4D6}" });
  const link = header.createEl("a", {
    cls: "bible-verse-ref",
    text: `${ref} (${verse.translation})`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
  const body = el.createDiv({ cls: "bible-verse-body" });
  body.createEl("p", { cls: "bible-verse-text", text: verse.text });
  if (verse.copyright) {
    el.createDiv({ cls: "bible-verse-copyright", text: verse.copyright });
  }
}
function renderBlockquote(el, ref, verse, url) {
  const body = el.createDiv({ cls: "bible-verse-body" });
  body.createEl("p", { cls: "bible-verse-text", text: verse.text });
  const footer = el.createDiv({ cls: "bible-verse-footer" });
  footer.createSpan({ text: "\u2014 " });
  const link = footer.createEl("a", {
    cls: "bible-verse-ref",
    text: `${ref} (${verse.translation})`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
  if (verse.copyright) {
    el.createDiv({ cls: "bible-verse-copyright", text: verse.copyright });
  }
}
function renderInline(el, ref, verse, url) {
  el.createSpan({ cls: "bible-verse-text", text: `"${verse.text}" ` });
  const link = el.createEl("a", {
    cls: "bible-verse-ref",
    text: `(${ref}, ${verse.translation})`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
  if (verse.copyright) {
    el.createSpan({ cls: "bible-verse-copyright", text: ` ${verse.copyright}` });
  }
}
function renderLink(container, ref, translation, website) {
  const refStr = formatReference(ref);
  const url = generateLink(ref, translation, website);
  const span = container.createSpan({ cls: "bible-verse bible-verse-link" });
  const link = span.createEl("a", {
    cls: "bible-verse-ref",
    text: `\u{1F4D6} ${refStr}`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
}
function renderComparison(container, ref, verses, website) {
  const wrapper = container.createDiv({ cls: "bible-verse-comparison" });
  const refStr = formatReference(ref);
  wrapper.createEl("div", {
    cls: "bible-verse-comparison-header",
    text: refStr
  });
  const grid = wrapper.createDiv({ cls: "bible-verse-comparison-grid" });
  for (const verse of verses) {
    const col = grid.createDiv({ cls: "bible-verse-comparison-col" });
    const url = generateLink(ref, verse.translation, website);
    const header = col.createDiv({ cls: "bible-verse-comparison-trans" });
    const link = header.createEl("a", {
      text: verse.translation,
      href: url
    });
    link.setAttr("target", "_blank");
    link.setAttr("rel", "noopener");
    col.createEl("p", { cls: "bible-verse-text", text: verse.text });
    if (verse.copyright) {
      col.createDiv({ cls: "bible-verse-copyright", text: verse.copyright });
    }
  }
}
function renderError(container, message) {
  container.createDiv({
    cls: "bible-verse bible-verse-error",
    text: `Bible Verse: ${message}`
  });
}

// src/quick-insert-modal.ts
var import_obsidian3 = require("obsidian");
var QuickInsertModal = class extends import_obsidian3.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "Insert Bible Reference" });
    let inputValue = "";
    let openInBrowser = false;
    const statusEl = contentEl.createDiv({ cls: "bible-verse-quick-status" });
    const inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "Type a reference... (e.g., John 3:16)",
      cls: "bible-verse-quick-input"
    });
    inputEl.style.width = "100%";
    inputEl.style.padding = "8px";
    inputEl.style.fontSize = "1.1em";
    inputEl.focus();
    inputEl.addEventListener("input", () => {
      inputValue = inputEl.value;
      const ref = parseReference(inputValue);
      if (ref) {
        statusEl.setText("\u2713 " + formatReference(ref));
        statusEl.style.color = "var(--text-success, green)";
        inputEl.style.borderColor = "var(--text-success, green)";
      } else if (inputValue.length > 0) {
        statusEl.setText("Invalid reference");
        statusEl.style.color = "var(--text-error, red)";
        inputEl.style.borderColor = "var(--text-error, red)";
      } else {
        statusEl.setText("");
        inputEl.style.borderColor = "";
      }
    });
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        const ref = parseReference(inputValue);
        if (ref) {
          this.onSubmit(`{${formatReference(ref)}}`, openInBrowser);
          this.close();
        }
      }
    });
    new import_obsidian3.Setting(contentEl).setName("Also open on Bible site").addToggle((toggle) => toggle.onChange((val) => {
      openInBrowser = val;
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/suggest.ts
var import_obsidian4 = require("obsidian");
var BibleReferenceSuggest = class extends import_obsidian4.EditorSuggest {
  constructor(app, plugin) {
    super(app);
    // Canonical book list in canonical order (Genesis → Revelation)
    this.books = Object.keys(USFM_CODES);
    this.plugin = plugin;
    this.limit = 10;
  }
  /**
   * Decide whether to show suggestions for the current cursor position.
   * Returns null if the cursor is not inside an unclosed {…} block.
   */
  onTrigger(cursor, editor, _file) {
    const line = editor.getLine(cursor.line);
    const beforeCursor = line.substring(0, cursor.ch);
    const openBrace = beforeCursor.lastIndexOf("{");
    if (openBrace === -1)
      return null;
    const afterOpen = beforeCursor.substring(openBrace + 1);
    if (afterOpen.includes("}"))
      return null;
    if (afterOpen.length === 0)
      return null;
    return {
      start: { line: cursor.line, ch: openBrace + 1 },
      end: cursor,
      query: afterOpen
    };
  }
  /**
   * Return matching suggestions for the current query.
   *
   * If the query already parses as a valid Bible reference, returns it as a
   * single "confirm" suggestion so the user can press Enter to close the block.
   * Otherwise, returns matching book names.
   */
  getSuggestions(context) {
    const query = context.query.trim();
    if (query.length === 0)
      return [];
    if (/\d/.test(query)) {
      if (query.includes(",")) {
        const parts = query.split(",");
        const refPart = parts.slice(0, -1).join(",").trim();
        const modPart = parts[parts.length - 1].trim().toLowerCase();
        const ref2 = parseReference(refPart);
        if (ref2) {
          const suggestions = [];
          for (const trans of HELLOAO_TRANSLATIONS) {
            if (trans.abbreviation.toLowerCase().startsWith(modPart)) {
              suggestions.push(`${refPart}, ${trans.abbreviation}`);
            }
          }
          for (const style of KNOWN_STYLES) {
            if (style.toLowerCase().startsWith(modPart)) {
              suggestions.push(`${refPart}, ${style}`);
            }
          }
          return suggestions.slice(0, this.limit);
        }
      }
      const ref = parseReference(query);
      if (ref) {
        return [formatReference(ref)];
      }
    }
    const typed = query.toLowerCase();
    const results = [];
    const seen = /* @__PURE__ */ new Set();
    for (const book of this.books) {
      if (book.toLowerCase().startsWith(typed)) {
        results.push(book);
        seen.add(book);
      }
    }
    for (const [alias, canonical] of Object.entries(BOOK_ALIASES)) {
      if (!seen.has(canonical) && alias.startsWith(typed)) {
        results.push(canonical);
        seen.add(canonical);
      }
    }
    if (results.length < 5) {
      for (const book of this.books) {
        if (!seen.has(book) && book.toLowerCase().includes(typed)) {
          results.push(book);
          seen.add(book);
        }
      }
    }
    return results.slice(0, this.limit);
  }
  /** Render a single suggestion row in the dropdown. */
  renderSuggestion(value, el) {
    el.createEl("span", { cls: "bible-suggest-icon", text: "\u{1F4D6} " });
    el.createEl("span", { cls: "bible-suggest-text", text: value });
  }
  /**
   * Insert the selected suggestion into the editor.
   *
   * - Complete reference (has a digit): replaces the typed content and closes
   *   the braces, moving the cursor past the }.
   * - Book name only: replaces the typed content with "Book " so the user can
   *   continue typing the chapter and verse.
   */
  selectSuggestion(value, _evt) {
    const { context } = this;
    if (!context)
      return;
    const editor = context.editor;
    const line = editor.getLine(context.start.line);
    const charAfterEnd = line[context.end.ch];
    const hasClosingBrace = charAfterEnd === "}";
    const isCompleteRef = /\d/.test(value);
    if (isCompleteRef) {
      if (hasClosingBrace) {
        editor.replaceRange(value, context.start, context.end);
        editor.setCursor({
          line: context.start.line,
          ch: context.start.ch + value.length + 1
          // +1 to land after the }
        });
      } else {
        editor.replaceRange(value + "}", context.start, context.end);
        editor.setCursor({
          line: context.start.line,
          ch: context.start.ch + value.length + 1
        });
      }
    } else {
      editor.replaceRange(value + " ", context.start, context.end);
      editor.setCursor({
        line: context.start.line,
        ch: context.start.ch + value.length + 1
      });
    }
  }
};

// src/view-plugin.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var INLINE_RE = /\{([A-Za-z0-9][^}\n]*)\}/g;
var verseFetchedEffect = import_state.StateEffect.define();
var BibleVerseWidget = class extends import_view.WidgetType {
  constructor(spec) {
    super();
    this.spec = spec;
  }
  toDOM(view) {
    var _a;
    const container = document.createElement("span");
    container.className = "bible-verse-livepreview";
    if (this.spec.cachedVerse) {
      renderVerse(
        container,
        this.spec.ref,
        this.spec.cachedVerse,
        (_a = this.spec.styleOverride) != null ? _a : this.spec.plugin.settings.displayStyle,
        this.spec.plugin.settings.preferredWebsite
      );
    } else {
      this.renderPill(container);
      this.fetchAndUpdate(container, view);
    }
    return container;
  }
  renderPill(container) {
    const a = document.createElement("a");
    a.className = "bible-verse-pill";
    a.textContent = "\u{1F4D6} " + this.spec.label;
    a.href = this.spec.href;
    a.target = "_blank";
    a.rel = "noopener";
    a.addEventListener("mousedown", (e) => e.preventDefault());
    container.appendChild(a);
  }
  async fetchAndUpdate(container, view) {
    var _a;
    const { plugin, ref, translations } = this.spec;
    try {
      let verse;
      if (translations.length >= 2) {
        const id = plugin.resolveTranslationIdPublic(translations[0]);
        const abbr = plugin.getTranslationAbbrPublic(id);
        verse = await plugin.api.getPassage(ref, id, abbr, {
          showVerseNumbers: plugin.settings.showVerseNumbers,
          verseNewLine: plugin.settings.verseNewLine
        });
      } else {
        const id = translations.length === 1 ? plugin.resolveTranslationIdPublic(translations[0]) : plugin.settings.defaultTranslation;
        const abbr = plugin.getTranslationAbbrPublic(id);
        verse = await plugin.api.getPassage(ref, id, abbr, {
          showVerseNumbers: plugin.settings.showVerseNumbers,
          verseNewLine: plugin.settings.verseNewLine
        });
      }
      container.empty();
      renderVerse(
        container,
        ref,
        verse,
        (_a = this.spec.styleOverride) != null ? _a : plugin.settings.displayStyle,
        plugin.settings.preferredWebsite
      );
      view.dispatch({ effects: verseFetchedEffect.of(void 0) });
    } catch (e) {
      console.error("Bible Verse Live Preview: fetch failed", e);
      container.empty();
      renderError(container, `Could not load ${formatReference(ref)}.`);
    }
  }
  /**
   * Two widgets are equal if they would render identically.
   * Comparing cachedVerse reference is enough — once a verse enters the cache
   * the same object is returned on subsequent lookups.
   */
  eq(other) {
    return this.spec.label === other.spec.label && this.spec.cachedVerse === other.spec.cachedVerse && this.spec.styleOverride === other.spec.styleOverride;
  }
  /**
   * Controls which events CodeMirror handles vs. what the widget DOM handles.
   *
   * Default CM6 behavior on mousedown inside a replace-decoration is to place
   * the caret at the token position, which un-replaces the widget. That made
   * clicking the rendered reference anchor feel broken — the user clicked
   * "John 3:16 (KJV)" expecting BibleHub to open, but instead saw raw "{John 3:16}".
   *
   * Fix: when a pointer event originates on an <a> inside the widget, return true
   * so CM leaves the event alone and the browser navigates the link normally.
   * For non-anchor targets (verse body text, callout background, etc.) mousedown
   * still returns false so the caret can move into the token for editing.
   *
   * click/auxclick always return true so left-click, middle-click (open in new
   * tab), and Ctrl/Cmd+click all reach the anchor default handler.
   */
  ignoreEvent(event) {
    const target = event.target;
    const isAnchorEvent = !!(target && target.closest("a"));
    if (event.type === "mousedown") {
      return isAnchorEvent;
    }
    return true;
  }
};
function selectionOverlaps(ranges, from, to) {
  for (const sel of ranges) {
    if (sel.from <= to && sel.to >= from)
      return true;
  }
  return false;
}
function buildViewPlugin(plugin) {
  return import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.decorations = this.buildDecorations(view);
      }
      update(update) {
        const needsRebuild = update.docChanged || update.viewportChanged || update.selectionSet || update.transactions.some(
          (tr) => tr.effects.some((e) => e.is(verseFetchedEffect))
        );
        if (needsRebuild) {
          this.decorations = this.buildDecorations(update.view);
        }
      }
      buildDecorations(view) {
        var _a;
        const builder = new import_state.RangeSetBuilder();
        const selections = view.state.selection.ranges;
        for (const { from, to } of view.visibleRanges) {
          const text = view.state.doc.sliceString(from, to);
          INLINE_RE.lastIndex = 0;
          let match;
          while ((match = INLINE_RE.exec(text)) !== null) {
            const tokenStart = from + match.index;
            const tokenEnd = tokenStart + match[0].length;
            if (selectionOverlaps(selections, tokenStart, tokenEnd))
              continue;
            const content = match[1].trim();
            const spec = parseInlineSpec(content);
            if (!spec)
              continue;
            const { ref, translations, styleOverride } = spec;
            const refLabel = formatReference(ref);
            let translationId;
            let abbr;
            if (translations.length >= 1) {
              translationId = plugin.resolveTranslationIdPublic(translations[0]);
              abbr = plugin.getTranslationAbbrPublic(translationId);
            } else {
              translationId = plugin.settings.defaultTranslation;
              abbr = plugin.getTranslationAbbrPublic();
            }
            const cachedVerse = (_a = plugin.cache.get(abbr, refLabel)) != null ? _a : null;
            let label;
            if (translations.length === 0) {
              label = refLabel;
            } else if (translations.length === 1) {
              label = `${refLabel} (${translations[0]})`;
            } else {
              label = `${refLabel} (${translations.join(" | ")})`;
            }
            const href = plugin.generateLinkPublic(ref, abbr);
            const widget = new BibleVerseWidget({
              label,
              href,
              ref,
              translations,
              styleOverride,
              cachedVerse,
              plugin
            });
            builder.add(
              tokenStart,
              tokenEnd,
              import_view.Decoration.replace({ widget })
            );
          }
        }
        return builder.finish();
      }
    },
    { decorations: (v) => v.decorations }
  );
}

// src/main.ts
var BibleVersePlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.api = null;
    this.cache = null;
    this.baker = null;
  }
  async onload() {
    await this.loadSettings();
    this.updateStyles();
    this.cache = new VerseCache(this);
    await this.cache.load();
    this.api = new BibleApi(this.cache);
    this.baker = new Baker(this.app);
    this.registerMarkdownPostProcessor(this.inlinePostProcessor.bind(this));
    this.registerEditorSuggest(new BibleReferenceSuggest(this.app, this));
    this.registerEditorExtension(buildViewPlugin(this));
    this.registerMarkdownCodeBlockProcessor("bible", this.codeBlockProcessor.bind(this));
    this.addSettingTab(new BibleVerseSettingTab(this.app, this));
    this.addCommand({
      id: "bake-current-note",
      name: "Bake all verses in this note",
      editorCallback: async (editor) => {
        const content = editor.getValue();
        const newContent = await this.baker.bakeFile(
          content,
          this.settings.bakeInline,
          (ref) => this.fetchVerse(ref)
        );
        if (newContent !== content) {
          editor.setValue(newContent);
          new import_obsidian5.Notice("Bible verses baked into note.");
        } else {
          new import_obsidian5.Notice("No verses to bake.");
        }
      }
    });
    this.addCommand({
      id: "refresh-current-note",
      name: "Refresh baked verses in this note",
      editorCallback: async (editor) => {
        let content = editor.getValue();
        content = this.baker.stripBakedText(content);
        const newContent = await this.baker.bakeFile(
          content,
          this.settings.bakeInline,
          (ref) => this.fetchVerse(ref)
        );
        editor.setValue(newContent);
        new import_obsidian5.Notice("Bible verses refreshed.");
      }
    });
    this.addCommand({
      id: "refresh-vault",
      name: "Refresh all baked verses in vault",
      callback: async () => {
        const count = await this.baker.processVault(
          "bake",
          this.settings.bakeInline,
          (ref) => this.fetchVerse(ref)
        );
        new import_obsidian5.Notice(`Refreshed baked verses in ${count} files.`);
      }
    });
    this.addCommand({
      id: "bake-vault",
      name: "Bake all existing verses across vault",
      callback: async () => {
        const count = await this.baker.processVault(
          "bake",
          this.settings.bakeInline,
          (ref) => this.fetchVerse(ref)
        );
        new import_obsidian5.Notice(`Baked verses in ${count} files.`);
      }
    });
    this.addCommand({
      id: "strip-vault",
      name: "Strip baked text from all notes",
      callback: async () => {
        const count = await this.baker.processVault("strip", false);
        new import_obsidian5.Notice(`Stripped baked text from ${count} files.`);
      }
    });
    this.addCommand({
      id: "quick-insert",
      name: "Quick insert reference",
      callback: () => {
        const modal = new QuickInsertModal(this.app, (refStr, openInBrowser) => {
          var _a;
          const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
          if (editor) {
            editor.replaceSelection(refStr);
          }
          if (openInBrowser) {
            const inner = refStr.replace(/^\{|\}$/g, "");
            const ref = parseReference(inner);
            if (ref) {
              const abbr = this.getTranslationAbbr();
              const url = generateLink(ref, abbr, this.settings.preferredWebsite);
              window.open(url, "_blank");
            }
          }
        });
        modal.open();
      }
    });
    this.addCommand({
      id: "search-selection",
      name: "Search Bible for selected text",
      editorCallback: (editor) => {
        const selection = editor.getSelection();
        if (!selection || selection.trim().length === 0) {
          new import_obsidian5.Notice("No text selected.");
          return;
        }
        navigator.clipboard.writeText(selection.trim());
        new import_obsidian5.Notice("Copied to clipboard. Opening search...");
        const abbr = this.getTranslationAbbr();
        const url = generateSearchUrl(selection.trim(), abbr, this.settings.preferredWebsite);
        window.open(url, "_blank");
      }
    });
    this.addCommand({
      id: "open-reference",
      name: "Open reference at cursor on Bible site",
      editorCallback: (editor) => {
        const cursor = editor.getCursor();
        const line = editor.getLine(cursor.line);
        const regex = /\{([A-Za-z0-9][^}\n]*)\}/g;
        let match;
        while ((match = regex.exec(line)) !== null) {
          const start = match.index;
          const end = start + match[0].length;
          if (cursor.ch >= start && cursor.ch <= end) {
            const spec = parseInlineSpec(match[1].trim());
            if (spec) {
              const abbr = spec.translations.length >= 1 ? this.getTranslationAbbr(this.resolveTranslationId(spec.translations[0])) : this.getTranslationAbbr();
              const url = generateLink(spec.ref, abbr, this.settings.preferredWebsite);
              window.open(url, "_blank");
              return;
            }
          }
        }
        new import_obsidian5.Notice("No Bible reference found at cursor.");
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  updateStyles() {
    document.body.style.setProperty(
      "--bible-verse-sidebar-top-padding",
      `${this.settings.sidebarTopPadding}em`
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Get a short abbreviation for the current translation.
   * Looks up from the HELLOAO_ABBREV map, falls back to the ID itself.
   */
  getTranslationAbbr(translationId) {
    var _a;
    const id = translationId != null ? translationId : this.settings.defaultTranslation;
    return (_a = HELLOAO_ABBREV[id]) != null ? _a : id;
  }
  /**
   * Fetch a verse using the current settings.
   * If network fetch fails, attempts to find a baked block in the active file as a fallback.
   */
  async fetchVerse(ref) {
    try {
      const verse = await this.api.getPassage(
        ref,
        this.settings.defaultTranslation,
        this.getTranslationAbbr(),
        {
          showVerseNumbers: this.settings.showVerseNumbers,
          verseNewLine: this.settings.verseNewLine
        }
      );
      if (verse)
        return verse;
    } catch (e) {
      console.error("Bible Verse: Fetch failed", e);
    }
    return null;
  }
  /**
   * Inline markdown postprocessor: finds bib:ref in rendered text and replaces them.
   */
  async inlinePostProcessor(el, ctx) {
    var _a, _b;
    const INLINE_REGEX = /\{([A-Za-z0-9][^}\n]*)\}/g;
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
    const nodesToProcess = [];
    let node;
    while (node = walker.nextNode()) {
      const text = node.textContent || "";
      const matches = [...text.matchAll(INLINE_REGEX)];
      if (matches.length > 0) {
        nodesToProcess.push({ node, matches });
      }
    }
    for (const { node: node2, matches } of nodesToProcess) {
      const text = node2.textContent || "";
      const frag = document.createDocumentFragment();
      let lastIndex = 0;
      for (const match of matches) {
        const matchIndex = match.index;
        if (matchIndex > lastIndex) {
          frag.appendChild(document.createTextNode(text.slice(lastIndex, matchIndex)));
        }
        const rawContent = match[1].trim();
        const spec = parseInlineSpec(rawContent);
        if (spec) {
          const { ref, translations } = spec;
          const span = document.createElement("span");
          span.className = "bible-verse-container";
          if (translations.length >= 2) {
            this.renderInlineComparison(span, ref, translations);
          } else {
            const translationId = translations.length === 1 ? this.resolveTranslationId(translations[0]) : this.settings.defaultTranslation;
            const abbr = translations.length === 1 ? this.getTranslationAbbr(translationId) : this.getTranslationAbbr();
            const style = (_a = spec.styleOverride) != null ? _a : this.settings.displayStyle;
            const cached = this.cache.get(abbr, formatReference(ref));
            if (cached) {
              renderVerse(span, ref, cached, style, this.settings.preferredWebsite);
            } else {
              renderLink(span, ref, abbr, this.settings.preferredWebsite);
              this.fetchAndRenderWithTranslation(span, ref, translationId, abbr, style);
            }
          }
          frag.appendChild(span);
          if (this.settings.persistVerseText && translations.length === 0) {
            this.handleBake(ctx, match[0], ref);
          }
        } else {
          frag.appendChild(document.createTextNode(match[0]));
        }
        lastIndex = matchIndex + match[0].length;
      }
      if (lastIndex < text.length) {
        frag.appendChild(document.createTextNode(text.slice(lastIndex)));
      }
      (_b = node2.parentNode) == null ? void 0 : _b.replaceChild(frag, node2);
    }
  }
  /**
   * Fetch a verse with a specific translation and update the rendered element.
   */
  async fetchAndRenderWithTranslation(container, ref, translationId, translationAbbr, style) {
    try {
      const verse = await this.api.getPassage(ref, translationId, translationAbbr, {
        showVerseNumbers: this.settings.showVerseNumbers,
        verseNewLine: this.settings.verseNewLine
      });
      container.empty();
      renderVerse(
        container,
        ref,
        verse,
        style != null ? style : this.settings.displayStyle,
        this.settings.preferredWebsite
      );
    } catch (e) {
      console.error("Bible Verse: Failed to fetch verse", e);
    }
  }
  /**
   * Render an inline comparison block for {ref, TRANS1, TRANS2} syntax.
   */
  async renderInlineComparison(container, ref, translations) {
    const verses = [];
    for (const trans of translations) {
      const id = this.resolveTranslationId(trans);
      const abbr = this.getTranslationAbbr(id);
      try {
        const verse = await this.api.getPassage(ref, id, abbr, {
          showVerseNumbers: this.settings.showVerseNumbers,
          verseNewLine: this.settings.verseNewLine
        });
        verses.push(verse);
      } catch (e) {
        console.error(`Bible Verse: Failed to fetch ${trans}`, e);
      }
    }
    if (verses.length > 0) {
      renderComparison(container, ref, verses, this.settings.preferredWebsite);
    } else {
      renderError(container, `Could not fetch translations for ${formatReference(ref)}.`);
    }
  }
  async handleBake(ctx, refMarker, ref) {
    const file = this.app.vault.getAbstractFileByPath(ctx.sourcePath);
    if (!(file instanceof import_obsidian5.TFile))
      return;
    if (!this.settings.bakeInline)
      return;
    const verse = await this.fetchVerse(ref);
    if (!verse)
      return;
    const content = await this.app.vault.read(file);
    const newContent = this.baker.bakeVerse(content, refMarker, verse, "inline");
    if (newContent !== content) {
      await this.app.vault.modify(file, newContent);
    }
  }
  /**
   * Code block processor for ```bible blocks.
   */
  async codeBlockProcessor(source, el, ctx) {
    el.empty();
    ctx.addChild(new import_obsidian5.MarkdownRenderChild(el));
    const lines = source.trim().split("\n");
    if (lines.length === 0) {
      renderError(el, "Empty bible code block.");
      return;
    }
    const refStr = lines[0].trim();
    const ref = parseReference(refStr);
    if (!ref) {
      renderError(el, `Could not parse reference: "${refStr}"`);
      return;
    }
    const config = {};
    let cachedText = null;
    let headerLinesCount = lines.length;
    const sepIdx = lines.indexOf("---");
    if (sepIdx > 0) {
      headerLinesCount = sepIdx;
      cachedText = lines.slice(sepIdx + 1).join("\n").trim();
    }
    for (let i = 1; i < headerLinesCount; i++) {
      const line = lines[i].trim();
      const colonIdx = line.indexOf(":");
      if (colonIdx > 0) {
        const key = line.substring(0, colonIdx).trim().toLowerCase();
        const value = line.substring(colonIdx + 1).trim();
        config[key] = value;
      }
    }
    if (config["compare"]) {
      const translations = config["compare"].split(",").map((s) => s.trim());
      await this.renderComparisonBlock(el, ref, translations);
      return;
    }
    const translationId = config["translation"] ? this.resolveTranslationId(config["translation"]) : this.settings.defaultTranslation;
    const translationAbbr = config["translation"] ? this.getTranslationAbbr(this.resolveTranslationId(config["translation"])) : this.getTranslationAbbr();
    const styleOverride = this.resolveStyleKey(config["style"]);
    try {
      let verse;
      if (cachedText) {
        verse = {
          reference: formatReference(ref),
          translation: translationAbbr,
          bibleId: translationId,
          text: cachedText,
          copyright: "",
          fetchedAt: Date.now()
        };
      } else {
        verse = await this.api.getPassage(ref, translationId, translationAbbr, {
          showVerseNumbers: this.settings.showVerseNumbers,
          verseNewLine: this.settings.verseNewLine
        });
      }
      renderVerse(
        el,
        ref,
        verse,
        styleOverride != null ? styleOverride : this.settings.displayStyle,
        this.settings.preferredWebsite
      );
    } catch (e) {
      renderError(el, `Failed to fetch ${formatReference(ref)}: ${e.message}`);
    }
  }
  /**
   * Map a raw `style:` config value (e.g. "sidebar", "CALLOUT") to a valid
   * DisplayStyle. Returns null for undefined or unrecognized values so the
   * caller can fall back to the plugin default.
   */
  resolveStyleKey(raw) {
    if (!raw)
      return null;
    const lower = raw.trim().toLowerCase();
    if (lower === "sidebar" || lower === "callout" || lower === "blockquote" || lower === "inline") {
      return lower;
    }
    return null;
  }
  /**
   * Render a comparison block with multiple translations.
   */
  async renderComparisonBlock(el, ref, translations) {
    const verses = [];
    for (const trans of translations) {
      const id = this.resolveTranslationId(trans);
      const abbr = this.getTranslationAbbr(id);
      try {
        const verse = await this.api.getPassage(ref, id, abbr, {
          showVerseNumbers: this.settings.showVerseNumbers,
          verseNewLine: this.settings.verseNewLine
        });
        verses.push(verse);
      } catch (e) {
        console.error(`Bible Verse: Failed to fetch ${trans}`, e);
      }
    }
    if (verses.length > 0) {
      renderComparison(el, ref, verses, this.settings.preferredWebsite);
    } else {
      renderError(el, "Failed to fetch any translations for comparison.");
    }
  }
  // ─── Public helpers for ViewPlugin ──────────────────────────────────────────
  /**
   * Public wrapper so the CM6 ViewPlugin can access translation abbreviations
   * without needing to import private method details.
   */
  getTranslationAbbrPublic(translationId) {
    return this.getTranslationAbbr(translationId);
  }
  /**
   * Public wrapper so the CM6 ViewPlugin can resolve translation IDs.
   */
  resolveTranslationIdPublic(abbr) {
    return this.resolveTranslationId(abbr);
  }
  /**
   * Public wrapper so the CM6 ViewPlugin can generate Bible website links.
   */
  generateLinkPublic(ref, translationAbbr) {
    return generateLink(ref, translationAbbr, this.settings.preferredWebsite);
  }
  // ─────────────────────────────────────────────────────────────────────────────
  /**
   * Resolve a translation abbreviation to a HelloAO translation ID.
   * Searches the curated list by abbreviation, then by ID directly.
   */
  resolveTranslationId(abbr) {
    const upper = abbr.toUpperCase();
    const match = HELLOAO_TRANSLATIONS.find(
      (t) => t.abbreviation.toUpperCase() === upper
    );
    if (match)
      return match.id;
    const byId = HELLOAO_TRANSLATIONS.find(
      (t) => t.id.toUpperCase() === upper
    );
    if (byId)
      return byId.id;
    return abbr;
  }
};
