/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BibleVersePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultTranslation: "eng_kjv",
  preferredWebsite: "BibleGateway",
  displayStyle: "callout",
  persistVerseText: false
};

// src/constants.ts
var USFM_CODES = {
  "Genesis": "GEN",
  "Exodus": "EXO",
  "Leviticus": "LEV",
  "Numbers": "NUM",
  "Deuteronomy": "DEU",
  "Joshua": "JOS",
  "Judges": "JDG",
  "Ruth": "RUT",
  "1 Samuel": "1SA",
  "2 Samuel": "2SA",
  "1 Kings": "1KI",
  "2 Kings": "2KI",
  "1 Chronicles": "1CH",
  "2 Chronicles": "2CH",
  "Ezra": "EZR",
  "Nehemiah": "NEH",
  "Esther": "EST",
  "Job": "JOB",
  "Psalms": "PSA",
  "Proverbs": "PRO",
  "Ecclesiastes": "ECC",
  "Song of Solomon": "SNG",
  "Isaiah": "ISA",
  "Jeremiah": "JER",
  "Lamentations": "LAM",
  "Ezekiel": "EZK",
  "Daniel": "DAN",
  "Hosea": "HOS",
  "Joel": "JOL",
  "Amos": "AMO",
  "Obadiah": "OBA",
  "Jonah": "JON",
  "Micah": "MIC",
  "Nahum": "NAM",
  "Habakkuk": "HAB",
  "Zephaniah": "ZEP",
  "Haggai": "HAG",
  "Zechariah": "ZEC",
  "Malachi": "MAL",
  "Matthew": "MAT",
  "Mark": "MRK",
  "Luke": "LUK",
  "John": "JHN",
  "Acts": "ACT",
  "Romans": "ROM",
  "1 Corinthians": "1CO",
  "2 Corinthians": "2CO",
  "Galatians": "GAL",
  "Ephesians": "EPH",
  "Philippians": "PHP",
  "Colossians": "COL",
  "1 Thessalonians": "1TH",
  "2 Thessalonians": "2TH",
  "1 Timothy": "1TI",
  "2 Timothy": "2TI",
  "Titus": "TIT",
  "Philemon": "PHM",
  "Hebrews": "HEB",
  "James": "JAS",
  "1 Peter": "1PE",
  "2 Peter": "2PE",
  "1 John": "1JN",
  "2 John": "2JN",
  "3 John": "3JN",
  "Jude": "JUD",
  "Revelation": "REV"
};
var BLB_CODES = {
  "Genesis": "gen",
  "Exodus": "exo",
  "Leviticus": "lev",
  "Numbers": "num",
  "Deuteronomy": "deu",
  "Joshua": "jos",
  "Judges": "jdg",
  "Ruth": "rut",
  "1 Samuel": "1sa",
  "2 Samuel": "2sa",
  "1 Kings": "1ki",
  "2 Kings": "2ki",
  "1 Chronicles": "1ch",
  "2 Chronicles": "2ch",
  "Ezra": "ezr",
  "Nehemiah": "neh",
  "Esther": "est",
  "Job": "job",
  "Psalms": "psa",
  "Proverbs": "pro",
  "Ecclesiastes": "ecc",
  "Song of Solomon": "sng",
  "Isaiah": "isa",
  "Jeremiah": "jer",
  "Lamentations": "lam",
  "Ezekiel": "eze",
  "Daniel": "dan",
  "Hosea": "hos",
  "Joel": "joe",
  "Amos": "amo",
  "Obadiah": "oba",
  "Jonah": "jon",
  "Micah": "mic",
  "Nahum": "nah",
  "Habakkuk": "hab",
  "Zephaniah": "zep",
  "Haggai": "hag",
  "Zechariah": "zec",
  "Malachi": "mal",
  "Matthew": "mat",
  "Mark": "mar",
  "Luke": "luk",
  "John": "jhn",
  "Acts": "act",
  "Romans": "rom",
  "1 Corinthians": "1co",
  "2 Corinthians": "2co",
  "Galatians": "gal",
  "Ephesians": "eph",
  "Philippians": "php",
  "Colossians": "col",
  "1 Thessalonians": "1th",
  "2 Thessalonians": "2th",
  "1 Timothy": "1ti",
  "2 Timothy": "2ti",
  "Titus": "tit",
  "Philemon": "phm",
  "Hebrews": "heb",
  "James": "jas",
  "1 Peter": "1pe",
  "2 Peter": "2pe",
  "1 John": "1jn",
  "2 John": "2jn",
  "3 John": "3jn",
  "Jude": "jud",
  "Revelation": "rev"
};
var BIBLEHUB_SLUGS = {
  "Genesis": "genesis",
  "Exodus": "exodus",
  "Leviticus": "leviticus",
  "Numbers": "numbers",
  "Deuteronomy": "deuteronomy",
  "Joshua": "joshua",
  "Judges": "judges",
  "Ruth": "ruth",
  "1 Samuel": "1_samuel",
  "2 Samuel": "2_samuel",
  "1 Kings": "1_kings",
  "2 Kings": "2_kings",
  "1 Chronicles": "1_chronicles",
  "2 Chronicles": "2_chronicles",
  "Ezra": "ezra",
  "Nehemiah": "nehemiah",
  "Esther": "esther",
  "Job": "job",
  "Psalms": "psalms",
  "Proverbs": "proverbs",
  "Ecclesiastes": "ecclesiastes",
  "Song of Solomon": "songs",
  "Isaiah": "isaiah",
  "Jeremiah": "jeremiah",
  "Lamentations": "lamentations",
  "Ezekiel": "ezekiel",
  "Daniel": "daniel",
  "Hosea": "hosea",
  "Joel": "joel",
  "Amos": "amos",
  "Obadiah": "obadiah",
  "Jonah": "jonah",
  "Micah": "micah",
  "Nahum": "nahum",
  "Habakkuk": "habakkuk",
  "Zephaniah": "zephaniah",
  "Haggai": "haggai",
  "Zechariah": "zechariah",
  "Malachi": "malachi",
  "Matthew": "matthew",
  "Mark": "mark",
  "Luke": "luke",
  "John": "john",
  "Acts": "acts",
  "Romans": "romans",
  "1 Corinthians": "1_corinthians",
  "2 Corinthians": "2_corinthians",
  "Galatians": "galatians",
  "Ephesians": "ephesians",
  "Philippians": "philippians",
  "Colossians": "colossians",
  "1 Thessalonians": "1_thessalonians",
  "2 Thessalonians": "2_thessalonians",
  "1 Timothy": "1_timothy",
  "2 Timothy": "2_timothy",
  "Titus": "titus",
  "Philemon": "philemon",
  "Hebrews": "hebrews",
  "James": "james",
  "1 Peter": "1_peter",
  "2 Peter": "2_peter",
  "1 John": "1_john",
  "2 John": "2_john",
  "3 John": "3_john",
  "Jude": "jude",
  "Revelation": "revelation"
};
var BIBLE_COM_TRANSLATION_IDS = {
  "KJV": 1,
  "ESV": 59,
  "NASB": 100,
  "NIV": 111,
  "NKJV": 114,
  "NLT": 116,
  "AMP": 1588,
  "CSB": 1713,
  "MSG": 97,
  "RSV": 2020
};
var HELLOAO_TRANSLATIONS = [
  { id: "eng_kjv", name: "King James Version (KJV)", abbreviation: "KJV" },
  { id: "BSB", name: "Berean Standard Bible (BSB)", abbreviation: "BSB" },
  { id: "eng_asv", name: "American Standard Version (ASV)", abbreviation: "ASV" },
  { id: "eng_web", name: "World English Bible (WEB)", abbreviation: "WEB" },
  { id: "eng_net", name: "NET Bible (NET)", abbreviation: "NET" },
  { id: "eng_dby", name: "Darby Translation (DARBY)", abbreviation: "DARBY" },
  { id: "eng_dra", name: "Douay-Rheims 1899 (DRB)", abbreviation: "DRB" },
  { id: "eng_rv5", name: "Revised Version (ERV)", abbreviation: "ERV" },
  { id: "eng_kja", name: "King James + Apocrypha (KJV+)", abbreviation: "KJV+" },
  { id: "eng_wbs", name: "Webster Bible (WBT)", abbreviation: "WBT" },
  { id: "eng_ylt", name: "Young's Literal Translation (YLT)", abbreviation: "YLT" },
  { id: "eng_bbe", name: "Bible in Basic English (BBE)", abbreviation: "BBE" },
  { id: "eng_fbv", name: "Free Bible Version (FBV)", abbreviation: "FBV" },
  { id: "eng_lsv", name: "Literal Standard Version (LSV)", abbreviation: "LSV" },
  { id: "eng_msb", name: "Majority Standard Bible (MSB)", abbreviation: "MSB" },
  { id: "ENGWEBP", name: "World English Bible (WEB-P)", abbreviation: "WEBP" },
  { id: "eng_gnv", name: "Geneva Bible 1599 (GNV)", abbreviation: "GNV" },
  { id: "eng_ojb", name: "Orthodox Jewish Bible (OJB)", abbreviation: "OJB" }
];
var HELLOAO_ABBREV = Object.fromEntries(
  HELLOAO_TRANSLATIONS.map((t) => [t.id, t.abbreviation])
);
var BOOK_ALIASES = {
  // Psalm vs Psalms
  "psalm": "Psalms",
  "psalms": "Psalms",
  "ps": "Psalms",
  "psa": "Psalms",
  // Song of Solomon variations
  "song of solomon": "Song of Solomon",
  "song of songs": "Song of Solomon",
  "songs": "Song of Solomon",
  "sos": "Song of Solomon",
  "sng": "Song of Solomon",
  "song": "Song of Solomon",
  // Genesis
  "genesis": "Genesis",
  "gen": "Genesis",
  // Exodus
  "exodus": "Exodus",
  "exod": "Exodus",
  "exo": "Exodus",
  "ex": "Exodus",
  // Leviticus
  "leviticus": "Leviticus",
  "lev": "Leviticus",
  // Numbers
  "numbers": "Numbers",
  "num": "Numbers",
  // Deuteronomy
  "deuteronomy": "Deuteronomy",
  "deut": "Deuteronomy",
  "deu": "Deuteronomy",
  "dt": "Deuteronomy",
  // Joshua
  "joshua": "Joshua",
  "josh": "Joshua",
  "jos": "Joshua",
  // Judges
  "judges": "Judges",
  "judg": "Judges",
  "jdg": "Judges",
  // Ruth
  "ruth": "Ruth",
  "rut": "Ruth",
  // Samuel
  "1 samuel": "1 Samuel",
  "1samuel": "1 Samuel",
  "1 sam": "1 Samuel",
  "1sam": "1 Samuel",
  "1sa": "1 Samuel",
  "2 samuel": "2 Samuel",
  "2samuel": "2 Samuel",
  "2 sam": "2 Samuel",
  "2sam": "2 Samuel",
  "2sa": "2 Samuel",
  // Kings
  "1 kings": "1 Kings",
  "1kings": "1 Kings",
  "1 kgs": "1 Kings",
  "1kgs": "1 Kings",
  "1ki": "1 Kings",
  "2 kings": "2 Kings",
  "2kings": "2 Kings",
  "2 kgs": "2 Kings",
  "2kgs": "2 Kings",
  "2ki": "2 Kings",
  // Chronicles
  "1 chronicles": "1 Chronicles",
  "1chronicles": "1 Chronicles",
  "1 chr": "1 Chronicles",
  "1chr": "1 Chronicles",
  "1ch": "1 Chronicles",
  "2 chronicles": "2 Chronicles",
  "2chronicles": "2 Chronicles",
  "2 chr": "2 Chronicles",
  "2chr": "2 Chronicles",
  "2ch": "2 Chronicles",
  // Ezra
  "ezra": "Ezra",
  "ezr": "Ezra",
  // Nehemiah
  "nehemiah": "Nehemiah",
  "neh": "Nehemiah",
  // Esther
  "esther": "Esther",
  "est": "Esther",
  // Job
  "job": "Job",
  // Proverbs
  "proverbs": "Proverbs",
  "prov": "Proverbs",
  "pro": "Proverbs",
  "pr": "Proverbs",
  // Ecclesiastes
  "ecclesiastes": "Ecclesiastes",
  "eccl": "Ecclesiastes",
  "ecc": "Ecclesiastes",
  "eccles": "Ecclesiastes",
  // Isaiah
  "isaiah": "Isaiah",
  "isa": "Isaiah",
  "is": "Isaiah",
  // Jeremiah
  "jeremiah": "Jeremiah",
  "jer": "Jeremiah",
  // Lamentations
  "lamentations": "Lamentations",
  "lam": "Lamentations",
  // Ezekiel
  "ezekiel": "Ezekiel",
  "ezek": "Ezekiel",
  "eze": "Ezekiel",
  "ezk": "Ezekiel",
  // Daniel
  "daniel": "Daniel",
  "dan": "Daniel",
  // Hosea
  "hosea": "Hosea",
  "hos": "Hosea",
  // Joel
  "joel": "Joel",
  "joe": "Joel",
  // Amos
  "amos": "Amos",
  // Obadiah
  "obadiah": "Obadiah",
  "oba": "Obadiah",
  "obad": "Obadiah",
  // Jonah
  "jonah": "Jonah",
  "jon": "Jonah",
  // Micah
  "micah": "Micah",
  "mic": "Micah",
  // Nahum
  "nahum": "Nahum",
  "nah": "Nahum",
  "nam": "Nahum",
  // Habakkuk
  "habakkuk": "Habakkuk",
  "hab": "Habakkuk",
  // Zephaniah
  "zephaniah": "Zephaniah",
  "zeph": "Zephaniah",
  "zep": "Zephaniah",
  // Haggai
  "haggai": "Haggai",
  "hag": "Haggai",
  // Zechariah
  "zechariah": "Zechariah",
  "zech": "Zechariah",
  "zec": "Zechariah",
  // Malachi
  "malachi": "Malachi",
  "mal": "Malachi",
  // Matthew
  "matthew": "Matthew",
  "matt": "Matthew",
  "mat": "Matthew",
  "mt": "Matthew",
  // Mark
  "mark": "Mark",
  "mrk": "Mark",
  "mk": "Mark",
  // Luke
  "luke": "Luke",
  "luk": "Luke",
  "lk": "Luke",
  // John (not 1/2/3 John)
  "john": "John",
  "jhn": "John",
  "jn": "John",
  // Acts
  "acts": "Acts",
  "act": "Acts",
  // Romans
  "romans": "Romans",
  "rom": "Romans",
  "ro": "Romans",
  // Corinthians
  "1 corinthians": "1 Corinthians",
  "1corinthians": "1 Corinthians",
  "1 cor": "1 Corinthians",
  "1cor": "1 Corinthians",
  "1co": "1 Corinthians",
  "2 corinthians": "2 Corinthians",
  "2corinthians": "2 Corinthians",
  "2 cor": "2 Corinthians",
  "2cor": "2 Corinthians",
  "2co": "2 Corinthians",
  // Galatians
  "galatians": "Galatians",
  "gal": "Galatians",
  // Ephesians
  "ephesians": "Ephesians",
  "eph": "Ephesians",
  // Philippians
  "philippians": "Philippians",
  "phil": "Philippians",
  "php": "Philippians",
  // Colossians
  "colossians": "Colossians",
  "col": "Colossians",
  // Thessalonians
  "1 thessalonians": "1 Thessalonians",
  "1thessalonians": "1 Thessalonians",
  "1 thess": "1 Thessalonians",
  "1thess": "1 Thessalonians",
  "1th": "1 Thessalonians",
  "2 thessalonians": "2 Thessalonians",
  "2thessalonians": "2 Thessalonians",
  "2 thess": "2 Thessalonians",
  "2thess": "2 Thessalonians",
  "2th": "2 Thessalonians",
  // Timothy
  "1 timothy": "1 Timothy",
  "1timothy": "1 Timothy",
  "1 tim": "1 Timothy",
  "1tim": "1 Timothy",
  "1ti": "1 Timothy",
  "2 timothy": "2 Timothy",
  "2timothy": "2 Timothy",
  "2 tim": "2 Timothy",
  "2tim": "2 Timothy",
  "2ti": "2 Timothy",
  // Titus
  "titus": "Titus",
  "tit": "Titus",
  // Philemon
  "philemon": "Philemon",
  "phm": "Philemon",
  "phlm": "Philemon",
  // Hebrews
  "hebrews": "Hebrews",
  "heb": "Hebrews",
  // James
  "james": "James",
  "jas": "James",
  // Peter
  "1 peter": "1 Peter",
  "1peter": "1 Peter",
  "1 pet": "1 Peter",
  "1pet": "1 Peter",
  "1pe": "1 Peter",
  "2 peter": "2 Peter",
  "2peter": "2 Peter",
  "2 pet": "2 Peter",
  "2pet": "2 Peter",
  "2pe": "2 Peter",
  // John epistles
  "1 john": "1 John",
  "1john": "1 John",
  "1 jn": "1 John",
  "1jn": "1 John",
  "2 john": "2 John",
  "2john": "2 John",
  "2 jn": "2 John",
  "2jn": "2 John",
  "3 john": "3 John",
  "3john": "3 John",
  "3 jn": "3 John",
  "3jn": "3 John",
  // Jude
  "jude": "Jude",
  "jud": "Jude",
  // Revelation
  "revelation": "Revelation",
  "rev": "Revelation",
  "re": "Revelation"
};

// src/parser.ts
var REF_REGEX = /^(\d?\s?[A-Za-z]+(?:\s+(?:of\s+)?[A-Za-z]+)*)\s+(\d+)(?::(\d+)(?:-(\d+):(\d+)|-(\d+))?((?:,\s*\d+)*))?$/;
function normalizeBookName(raw) {
  var _a;
  const key = raw.trim().toLowerCase();
  return (_a = BOOK_ALIASES[key]) != null ? _a : null;
}
function parseReference(input) {
  const trimmed = input.trim();
  const match = trimmed.match(REF_REGEX);
  if (!match)
    return null;
  const rawBook = match[1];
  const chapter = parseInt(match[2], 10);
  const book = normalizeBookName(rawBook);
  if (!book)
    return null;
  if (match[3] === void 0) {
    return {
      book,
      chapter,
      startVerse: null,
      endVerse: null,
      additionalVerses: [],
      endChapter: null,
      raw: trimmed
    };
  }
  const startVerse = parseInt(match[3], 10);
  if (match[4] !== void 0 && match[5] !== void 0) {
    const endChapter = parseInt(match[4], 10);
    const endVerse2 = parseInt(match[5], 10);
    return {
      book,
      chapter,
      startVerse,
      endVerse: endVerse2,
      additionalVerses: [],
      endChapter,
      raw: trimmed
    };
  }
  const endVerse = match[6] !== void 0 ? parseInt(match[6], 10) : null;
  const additionalVerses = [];
  if (match[7]) {
    const parts = match[7].split(",").filter((s) => s.trim().length > 0);
    for (const part of parts) {
      const v = parseInt(part.trim(), 10);
      if (!isNaN(v))
        additionalVerses.push(v);
    }
  }
  return {
    book,
    chapter,
    startVerse,
    endVerse,
    additionalVerses,
    endChapter: null,
    raw: trimmed
  };
}
function formatReference(ref) {
  let s = `${ref.book} ${ref.chapter}`;
  if (ref.startVerse !== null) {
    s += `:${ref.startVerse}`;
    if (ref.endChapter !== null && ref.endVerse !== null) {
      s += `-${ref.endChapter}:${ref.endVerse}`;
    } else if (ref.endVerse !== null) {
      s += `-${ref.endVerse}`;
    }
    if (ref.additionalVerses.length > 0) {
      s += "," + ref.additionalVerses.join(",");
    }
  }
  return s;
}

// src/api.ts
var import_obsidian = require("obsidian");
var BASE_URL = "https://bible.helloao.org/api";
var BibleApi = class {
  constructor(cache) {
    this.cache = cache;
  }
  /**
   * Extract text from a HelloAO verse content array.
   * Content items can be plain strings or objects with a `text` property
   * (e.g. wordsOfJesus markers, footnotes). We extract only text content.
   */
  extractVerseText(content) {
    return content.map((item) => {
      if (typeof item === "string")
        return item;
      if (typeof item === "object" && item !== null && "text" in item) {
        return item.text;
      }
      return "";
    }).filter((s) => s.length > 0).join(" ");
  }
  /**
   * Determine which verses from the chapter are needed for this reference.
   * Returns a Set of verse numbers to include.
   */
  getRequestedVerses(ref) {
    if (ref.startVerse === null)
      return null;
    const verses = /* @__PURE__ */ new Set();
    if (ref.endVerse !== null && ref.endChapter === null) {
      for (let v = ref.startVerse; v <= ref.endVerse; v++) {
        verses.add(v);
      }
    } else if (ref.endVerse === null && ref.additionalVerses.length === 0) {
      verses.add(ref.startVerse);
    } else {
      if (ref.endVerse !== null) {
        for (let v = ref.startVerse; v <= ref.endVerse; v++) {
          verses.add(v);
        }
      } else {
        verses.add(ref.startVerse);
      }
      for (const v of ref.additionalVerses) {
        verses.add(v);
      }
    }
    return verses;
  }
  /**
   * Fetch a passage from HelloAO Bible API.
   * Fetches the whole chapter and extracts the requested verses client-side.
   * Returns cached version if available.
   */
  async getPassage(ref, translationId, translationAbbr) {
    var _a;
    const refStr = formatReference(ref);
    const cached = this.cache.get(translationAbbr, refStr);
    if (cached)
      return cached;
    const usfm = USFM_CODES[ref.book];
    if (!usfm)
      throw new Error(`Unknown book: ${ref.book}`);
    const url = `${BASE_URL}/${translationId}/${usfm}/${ref.chapter}.json`;
    const response = await (0, import_obsidian.requestUrl)({ url });
    if (response.status !== 200) {
      throw new Error(`HelloAO API returned status ${response.status}`);
    }
    const data = response.json;
    const chapterContent = data.chapter.content;
    const requestedVerses = this.getRequestedVerses(ref);
    const verseParts = [];
    for (const item of chapterContent) {
      if (typeof item === "object" && item !== null && item.type === "verse") {
        const verseItem = item;
        if (requestedVerses === null || requestedVerses.has(verseItem.number)) {
          const text2 = this.extractVerseText(verseItem.content);
          if (text2)
            verseParts.push(text2);
        }
      }
    }
    if (verseParts.length === 0) {
      throw new Error(`No verses found for ${refStr} in ${translationAbbr}`);
    }
    const text = verseParts.join(" ");
    const licenseUrl = (_a = data.translation) == null ? void 0 : _a.licenseUrl;
    const copyright = licenseUrl ? `License: ${licenseUrl}` : "";
    const entry = {
      reference: refStr,
      translation: translationAbbr,
      bibleId: translationId,
      text,
      copyright,
      fetchedAt: Date.now()
    };
    await this.cache.set(entry);
    return entry;
  }
};

// src/cache.ts
var VerseCache = class {
  constructor(plugin) {
    this.cache = /* @__PURE__ */ new Map();
    this.loaded = false;
    this.plugin = plugin;
    this.cacheDir = `${plugin.manifest.dir}/cache`;
  }
  /** Build a cache key from translation and reference */
  key(translation, reference) {
    return `${translation}:${reference}`.toLowerCase().replace(/\s+/g, "_");
  }
  /** Load the full cache index from disk */
  async load() {
    if (this.loaded)
      return;
    const adapter = this.plugin.app.vault.adapter;
    const exists = await adapter.exists(this.cacheDir);
    if (!exists) {
      await adapter.mkdir(this.cacheDir);
      this.loaded = true;
      return;
    }
    const files = await adapter.list(this.cacheDir);
    for (const file of files.files) {
      try {
        const data = await adapter.read(file);
        const entry = JSON.parse(data);
        const k = this.key(entry.translation, entry.reference);
        this.cache.set(k, entry);
      } catch (e) {
      }
    }
    this.loaded = true;
  }
  /** Get a cached verse, or null if not cached */
  get(translation, reference) {
    var _a;
    return (_a = this.cache.get(this.key(translation, reference))) != null ? _a : null;
  }
  /** Store a verse in the cache */
  async set(entry) {
    const k = this.key(entry.translation, entry.reference);
    this.cache.set(k, entry);
    const adapter = this.plugin.app.vault.adapter;
    const exists = await adapter.exists(this.cacheDir);
    if (!exists) {
      await adapter.mkdir(this.cacheDir);
    }
    const filePath = `${this.cacheDir}/${k}.json`;
    await adapter.write(filePath, JSON.stringify(entry, null, 2));
  }
  /** Check if a verse is cached */
  has(translation, reference) {
    return this.cache.has(this.key(translation, reference));
  }
  /** Clear the entire cache */
  async clear() {
    const adapter = this.plugin.app.vault.adapter;
    const exists = await adapter.exists(this.cacheDir);
    if (exists) {
      const files = await adapter.list(this.cacheDir);
      for (const file of files.files) {
        await adapter.remove(file);
      }
    }
    this.cache.clear();
  }
};

// src/baker.ts
var INLINE_REF_REGEX = /@\[([^\]]+)\]/g;
var Baker = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Extract all @[ref] references from note content.
   */
  extractReferences(content) {
    const results = [];
    let match;
    const regex = new RegExp(INLINE_REF_REGEX.source, "g");
    while ((match = regex.exec(content)) !== null) {
      const ref = parseReference(match[1]);
      if (ref) {
        results.push({ raw: match[0], ref, offset: match.index });
      }
    }
    return results;
  }
  /**
   * Bake a verse into the note content after its @[ref].
   * If already baked, update the baked block.
   */
  bakeVerse(content, refRaw, verse) {
    const bakedBlock = `
%%bible-baked|${verse.translation}%%
${verse.text}
%%end-bible%%`;
    const existingPattern = new RegExp(
      escapeRegex(refRaw) + "\\s*\\n%%bible-baked\\|[^%]+%%\\n[\\s\\S]*?%%end-bible%%",
      "g"
    );
    if (existingPattern.test(content)) {
      return content.replace(existingPattern, refRaw + bakedBlock);
    }
    return content.replace(refRaw, refRaw + bakedBlock);
  }
  /**
   * Strip all baked blocks from note content, leaving just the @[ref] markers.
   */
  stripBakedText(content) {
    return content.replace(
      /\s*\n%%bible-baked\|[^%]+%%\n[\s\S]*?%%end-bible%%/g,
      ""
    );
  }
  /**
   * Check if a @[ref] has a baked block following it.
   */
  hasBakedBlock(content, refRaw) {
    const pattern = new RegExp(
      escapeRegex(refRaw) + "\\s*\\n%%bible-baked\\|[^%]+%%\\n[\\s\\S]*?%%end-bible%%"
    );
    return pattern.test(content);
  }
  /**
   * Extract baked text for a reference if it exists.
   */
  extractBakedText(content, refRaw) {
    const pattern = new RegExp(
      escapeRegex(refRaw) + "\\s*\\n%%bible-baked\\|([^%]+)%%\\n([\\s\\S]*?)%%end-bible%%"
    );
    const match = content.match(pattern);
    if (!match)
      return null;
    return { translation: match[1], text: match[2].trim() };
  }
  /**
   * Bake all verses in a single file.
   * Returns the updated content.
   */
  async bakeFile(content, fetchVerse) {
    const refs = this.extractReferences(content);
    let result = content;
    for (const { raw, ref } of refs) {
      const verse = await fetchVerse(ref);
      if (verse) {
        result = this.bakeVerse(result, raw, verse);
      }
    }
    return result;
  }
  /**
   * Process all markdown files in the vault.
   */
  async processVault(action, fetchVerse) {
    const files = this.app.vault.getMarkdownFiles();
    let count = 0;
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const refs = this.extractReferences(content);
      if (refs.length === 0)
        continue;
      let newContent;
      if (action === "strip") {
        newContent = this.stripBakedText(content);
      } else if (fetchVerse) {
        newContent = await this.bakeFile(content, fetchVerse);
      } else {
        continue;
      }
      if (newContent !== content) {
        await this.app.vault.modify(file, newContent);
        count++;
      }
    }
    return count;
  }
};
function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// src/settings.ts
var import_obsidian2 = require("obsidian");
var BibleVerseSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Bible Verse Settings" });
    new import_obsidian2.Setting(containerEl).setName("Default Translation").setDesc("The Bible translation to use by default").addDropdown((dropdown) => {
      for (const t of HELLOAO_TRANSLATIONS) {
        dropdown.addOption(t.id, t.name);
      }
      dropdown.setValue(this.plugin.settings.defaultTranslation).onChange(async (value) => {
        this.plugin.settings.defaultTranslation = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Preferred Bible Website").setDesc("Which website to link verse references to").addDropdown(
      (dropdown) => dropdown.addOption("BibleHub", "BibleHub").addOption("BibleGateway", "BibleGateway").addOption("BlueLetter", "Blue Letter Bible").addOption("BibleCom", "Bible.com").setValue(this.plugin.settings.preferredWebsite).onChange(async (value) => {
        this.plugin.settings.preferredWebsite = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Display Style").setDesc("How verses are visually presented").addDropdown(
      (dropdown) => dropdown.addOption("sidebar", "Sidebar").addOption("callout", "Callout").addOption("blockquote", "Blockquote").addOption("inline", "Inline").setValue(this.plugin.settings.displayStyle).onChange(async (value) => {
        this.plugin.settings.displayStyle = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Persist Verse Text in Notes").setDesc(
      "When enabled, fetched verse text is automatically written into note source (bake mode)"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.persistVerseText).onChange(async (value) => {
        this.plugin.settings.persistVerseText = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/linker.ts
function generateLink(ref, translation, website) {
  switch (website) {
    case "BibleHub":
      return bibleHubUrl(ref, translation);
    case "BibleGateway":
      return bibleGatewayUrl(ref, translation);
    case "BlueLetter":
      return blueLetterUrl(ref, translation);
    case "BibleCom":
      return bibleComUrl(ref, translation);
  }
}
function generateSearchUrl(query, translation, website) {
  const encoded = encodeURIComponent(query);
  switch (website) {
    case "BibleHub":
      return `https://biblehub.com/search.php?q=${encoded}`;
    case "BibleGateway":
      return `https://www.biblegateway.com/quicksearch/?search=${encoded}&version=${translation}`;
    case "BlueLetter":
      return `https://www.blueletterbible.org/search/search.cfm?Criteria=${encoded}&t=${translation.toLowerCase()}`;
    case "BibleCom":
      return `https://www.bible.com/search/bible?query=${encoded}`;
  }
}
function bibleHubUrl(ref, translation) {
  var _a;
  const slug = BIBLEHUB_SLUGS[ref.book] || ref.book.toLowerCase().replace(/\s+/g, "_");
  const trans = translation.toLowerCase();
  const verse = (_a = ref.startVerse) != null ? _a : 1;
  return `https://biblehub.com/${trans}/${slug}/${ref.chapter}-${verse}.htm`;
}
function bibleGatewayUrl(ref, translation) {
  let search = ref.book + "+" + ref.chapter;
  if (ref.startVerse !== null) {
    search += "%3A" + ref.startVerse;
    if (ref.endChapter !== null && ref.endVerse !== null) {
      search += `-${ref.endChapter}%3A${ref.endVerse}`;
    } else if (ref.endVerse !== null) {
      search += `-${ref.endVerse}`;
    }
    if (ref.additionalVerses.length > 0) {
      search += "%2C" + ref.additionalVerses.join("%2C");
    }
  }
  search = search.replace(/\s+/g, "+");
  return `https://www.biblegateway.com/passage/?search=${search}&version=${translation}`;
}
function blueLetterUrl(ref, translation) {
  var _a;
  const code = BLB_CODES[ref.book] || ref.book.substring(0, 3).toLowerCase();
  const trans = translation.toLowerCase();
  const verse = (_a = ref.startVerse) != null ? _a : 1;
  return `https://www.blueletterbible.org/${trans}/${code}/${ref.chapter}/${verse}/`;
}
function bibleComUrl(ref, translation) {
  var _a;
  const usfm = USFM_CODES[ref.book] || ref.book.substring(0, 3).toUpperCase();
  const transId = BIBLE_COM_TRANSLATION_IDS[translation.toUpperCase()] || 1;
  const verse = (_a = ref.startVerse) != null ? _a : 1;
  return `https://www.bible.com/bible/${transId}/${usfm}.${ref.chapter}.${verse}`;
}

// src/renderer.ts
function renderVerse(container, ref, verse, style, website) {
  const wrapper = container.createDiv({ cls: `bible-verse bible-verse-${style}` });
  const refStr = formatReference(ref);
  const url = generateLink(ref, verse.translation, website);
  switch (style) {
    case "sidebar":
      renderSidebar(wrapper, refStr, verse, url);
      break;
    case "callout":
      renderCallout(wrapper, refStr, verse, url);
      break;
    case "blockquote":
      renderBlockquote(wrapper, refStr, verse, url);
      break;
    case "inline":
      renderInline(wrapper, refStr, verse, url);
      break;
  }
}
function renderSidebar(el, ref, verse, url) {
  const body = el.createDiv({ cls: "bible-verse-body" });
  body.createEl("p", { cls: "bible-verse-text", text: verse.text });
  const footer = el.createDiv({ cls: "bible-verse-footer" });
  const link = footer.createEl("a", {
    cls: "bible-verse-ref",
    text: `${ref} (${verse.translation})`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
  if (verse.copyright) {
    footer.createEl("span", { cls: "bible-verse-copyright", text: verse.copyright });
  }
}
function renderCallout(el, ref, verse, url) {
  const header = el.createDiv({ cls: "bible-verse-header" });
  header.createSpan({ cls: "bible-verse-icon", text: "\u{1F4D6}" });
  const link = header.createEl("a", {
    cls: "bible-verse-ref",
    text: `${ref} (${verse.translation})`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
  const body = el.createDiv({ cls: "bible-verse-body" });
  body.createEl("p", { cls: "bible-verse-text", text: verse.text });
  if (verse.copyright) {
    el.createDiv({ cls: "bible-verse-copyright", text: verse.copyright });
  }
}
function renderBlockquote(el, ref, verse, url) {
  const body = el.createDiv({ cls: "bible-verse-body" });
  body.createEl("p", { cls: "bible-verse-text", text: verse.text });
  const footer = el.createDiv({ cls: "bible-verse-footer" });
  footer.createSpan({ text: "\u2014 " });
  const link = footer.createEl("a", {
    cls: "bible-verse-ref",
    text: `${ref} (${verse.translation})`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
  if (verse.copyright) {
    el.createDiv({ cls: "bible-verse-copyright", text: verse.copyright });
  }
}
function renderInline(el, ref, verse, url) {
  el.createSpan({ cls: "bible-verse-text", text: `"${verse.text}" ` });
  const link = el.createEl("a", {
    cls: "bible-verse-ref",
    text: `(${ref}, ${verse.translation})`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
  if (verse.copyright) {
    el.createSpan({ cls: "bible-verse-copyright", text: ` ${verse.copyright}` });
  }
}
function renderLink(container, ref, translation, website) {
  const refStr = formatReference(ref);
  const url = generateLink(ref, translation, website);
  const span = container.createSpan({ cls: "bible-verse bible-verse-link" });
  const link = span.createEl("a", {
    cls: "bible-verse-ref",
    text: `\u{1F4D6} ${refStr}`,
    href: url
  });
  link.setAttr("target", "_blank");
  link.setAttr("rel", "noopener");
}
function renderComparison(container, ref, verses, website) {
  const wrapper = container.createDiv({ cls: "bible-verse-comparison" });
  const refStr = formatReference(ref);
  wrapper.createEl("div", {
    cls: "bible-verse-comparison-header",
    text: refStr
  });
  const grid = wrapper.createDiv({ cls: "bible-verse-comparison-grid" });
  for (const verse of verses) {
    const col = grid.createDiv({ cls: "bible-verse-comparison-col" });
    const url = generateLink(ref, verse.translation, website);
    const header = col.createDiv({ cls: "bible-verse-comparison-trans" });
    const link = header.createEl("a", {
      text: verse.translation,
      href: url
    });
    link.setAttr("target", "_blank");
    link.setAttr("rel", "noopener");
    col.createEl("p", { cls: "bible-verse-text", text: verse.text });
    if (verse.copyright) {
      col.createDiv({ cls: "bible-verse-copyright", text: verse.copyright });
    }
  }
}
function renderError(container, message) {
  container.createDiv({
    cls: "bible-verse bible-verse-error",
    text: `Bible Verse: ${message}`
  });
}

// src/quick-insert-modal.ts
var import_obsidian3 = require("obsidian");
var QuickInsertModal = class extends import_obsidian3.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "Insert Bible Reference" });
    let inputValue = "";
    let openInBrowser = false;
    const statusEl = contentEl.createDiv({ cls: "bible-verse-quick-status" });
    const inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "Type a reference... (e.g., John 3:16)",
      cls: "bible-verse-quick-input"
    });
    inputEl.style.width = "100%";
    inputEl.style.padding = "8px";
    inputEl.style.fontSize = "1.1em";
    inputEl.focus();
    inputEl.addEventListener("input", () => {
      inputValue = inputEl.value;
      const ref = parseReference(inputValue);
      if (ref) {
        statusEl.setText("\u2713 " + formatReference(ref));
        statusEl.style.color = "var(--text-success, green)";
        inputEl.style.borderColor = "var(--text-success, green)";
      } else if (inputValue.length > 0) {
        statusEl.setText("Invalid reference");
        statusEl.style.color = "var(--text-error, red)";
        inputEl.style.borderColor = "var(--text-error, red)";
      } else {
        statusEl.setText("");
        inputEl.style.borderColor = "";
      }
    });
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        const ref = parseReference(inputValue);
        if (ref) {
          this.onSubmit(formatReference(ref), openInBrowser);
          this.close();
        }
      }
    });
    new import_obsidian3.Setting(contentEl).setName("Also open on Bible site").addToggle((toggle) => toggle.onChange((val) => {
      openInBrowser = val;
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var BibleVersePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.api = null;
    this.cache = null;
    this.baker = null;
  }
  async onload() {
    await this.loadSettings();
    this.cache = new VerseCache(this);
    await this.cache.load();
    this.api = new BibleApi(this.cache);
    this.baker = new Baker(this.app);
    this.registerMarkdownPostProcessor(this.inlinePostProcessor.bind(this));
    this.registerMarkdownCodeBlockProcessor("bible", this.codeBlockProcessor.bind(this));
    this.addSettingTab(new BibleVerseSettingTab(this.app, this));
    this.addCommand({
      id: "bake-current-note",
      name: "Bake all verses in this note",
      editorCallback: async (editor) => {
        const content = editor.getValue();
        const newContent = await this.baker.bakeFile(
          content,
          (ref) => this.fetchVerse(ref)
        );
        if (newContent !== content) {
          editor.setValue(newContent);
          new import_obsidian4.Notice("Bible verses baked into note.");
        } else {
          new import_obsidian4.Notice("No verses to bake.");
        }
      }
    });
    this.addCommand({
      id: "refresh-current-note",
      name: "Refresh baked verses in this note",
      editorCallback: async (editor) => {
        let content = editor.getValue();
        content = this.baker.stripBakedText(content);
        const newContent = await this.baker.bakeFile(
          content,
          (ref) => this.fetchVerse(ref)
        );
        editor.setValue(newContent);
        new import_obsidian4.Notice("Bible verses refreshed.");
      }
    });
    this.addCommand({
      id: "refresh-vault",
      name: "Refresh all baked verses in vault",
      callback: async () => {
        const count = await this.baker.processVault(
          "bake",
          (ref) => this.fetchVerse(ref)
        );
        new import_obsidian4.Notice(`Refreshed baked verses in ${count} files.`);
      }
    });
    this.addCommand({
      id: "bake-vault",
      name: "Bake all existing verses across vault",
      callback: async () => {
        const count = await this.baker.processVault(
          "bake",
          (ref) => this.fetchVerse(ref)
        );
        new import_obsidian4.Notice(`Baked verses in ${count} files.`);
      }
    });
    this.addCommand({
      id: "strip-vault",
      name: "Strip baked text from all notes",
      callback: async () => {
        const count = await this.baker.processVault("strip");
        new import_obsidian4.Notice(`Stripped baked text from ${count} files.`);
      }
    });
    this.addCommand({
      id: "quick-insert",
      name: "Quick insert reference",
      callback: () => {
        const modal = new QuickInsertModal(this.app, (refStr, openInBrowser) => {
          var _a;
          const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
          if (editor) {
            editor.replaceSelection(`@[${refStr}]`);
          }
          if (openInBrowser) {
            const ref = parseReference(refStr);
            if (ref) {
              const abbr = this.getTranslationAbbr();
              const url = generateLink(ref, abbr, this.settings.preferredWebsite);
              window.open(url, "_blank");
            }
          }
        });
        modal.open();
      }
    });
    this.addCommand({
      id: "search-selection",
      name: "Search Bible for selected text",
      editorCallback: (editor) => {
        const selection = editor.getSelection();
        if (!selection || selection.trim().length === 0) {
          new import_obsidian4.Notice("No text selected.");
          return;
        }
        navigator.clipboard.writeText(selection.trim());
        new import_obsidian4.Notice("Copied to clipboard. Opening search...");
        const abbr = this.getTranslationAbbr();
        const url = generateSearchUrl(selection.trim(), abbr, this.settings.preferredWebsite);
        window.open(url, "_blank");
      }
    });
    this.addCommand({
      id: "open-reference",
      name: "Open reference at cursor on Bible site",
      editorCallback: (editor) => {
        const cursor = editor.getCursor();
        const line = editor.getLine(cursor.line);
        const regex = /@\[([^\]]+)\]/g;
        let match;
        while ((match = regex.exec(line)) !== null) {
          const start = match.index;
          const end = start + match[0].length;
          if (cursor.ch >= start && cursor.ch <= end) {
            const ref = parseReference(match[1]);
            if (ref) {
              const abbr = this.getTranslationAbbr();
              const url = generateLink(ref, abbr, this.settings.preferredWebsite);
              window.open(url, "_blank");
              return;
            }
          }
        }
        new import_obsidian4.Notice("No Bible reference found at cursor.");
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Get a short abbreviation for the current translation.
   * Looks up from the HELLOAO_ABBREV map, falls back to the ID itself.
   */
  getTranslationAbbr(translationId) {
    var _a;
    const id = translationId != null ? translationId : this.settings.defaultTranslation;
    return (_a = HELLOAO_ABBREV[id]) != null ? _a : id;
  }
  /**
   * Fetch a verse using the current settings.
   */
  async fetchVerse(ref) {
    try {
      return await this.api.getPassage(
        ref,
        this.settings.defaultTranslation,
        this.getTranslationAbbr()
      );
    } catch (e) {
      console.error("Bible Verse: Failed to fetch verse", e);
      return null;
    }
  }
  /**
   * Inline markdown postprocessor: finds @[ref] in rendered text and replaces them.
   */
  async inlinePostProcessor(el, ctx) {
    var _a;
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
    const nodesToProcess = [];
    let node;
    while (node = walker.nextNode()) {
      const text = node.textContent || "";
      const matches = [...text.matchAll(/@\[([^\]]+)\]/g)];
      if (matches.length > 0) {
        nodesToProcess.push({ node, matches });
      }
    }
    for (const { node: node2, matches } of nodesToProcess) {
      const text = node2.textContent || "";
      const frag = document.createDocumentFragment();
      let lastIndex = 0;
      for (const match of matches) {
        const matchIndex = match.index;
        if (matchIndex > lastIndex) {
          frag.appendChild(document.createTextNode(text.slice(lastIndex, matchIndex)));
        }
        const refStr = match[1];
        const ref = parseReference(refStr);
        if (ref) {
          const span = document.createElement("span");
          span.className = "bible-verse-container";
          const abbr = this.getTranslationAbbr();
          const cached = this.cache.get(abbr, formatReference(ref));
          if (cached) {
            renderVerse(
              span,
              ref,
              cached,
              this.settings.displayStyle,
              this.settings.preferredWebsite
            );
          } else {
            renderLink(span, ref, abbr, this.settings.preferredWebsite);
            this.fetchAndRender(span, ref);
          }
          frag.appendChild(span);
          if (this.settings.persistVerseText) {
            this.handleBake(ctx, refStr, ref);
          }
        } else {
          frag.appendChild(document.createTextNode(match[0]));
        }
        lastIndex = matchIndex + match[0].length;
      }
      if (lastIndex < text.length) {
        frag.appendChild(document.createTextNode(text.slice(lastIndex)));
      }
      (_a = node2.parentNode) == null ? void 0 : _a.replaceChild(frag, node2);
    }
  }
  /**
   * Fetch a verse and update the rendered element.
   */
  async fetchAndRender(container, ref) {
    const verse = await this.fetchVerse(ref);
    if (verse) {
      container.empty();
      renderVerse(
        container,
        ref,
        verse,
        this.settings.displayStyle,
        this.settings.preferredWebsite
      );
    }
  }
  /**
   * Handle automatic baking when persistVerseText is on.
   */
  async handleBake(ctx, rawRef, ref) {
    const file = this.app.vault.getAbstractFileByPath(ctx.sourcePath);
    if (!file || !(file instanceof (await import("obsidian")).TFile))
      return;
    const verse = await this.fetchVerse(ref);
    if (!verse)
      return;
    const content = await this.app.vault.read(file);
    const refMarker = `@[${rawRef}]`;
    if (this.baker.hasBakedBlock(content, refMarker))
      return;
    const newContent = this.baker.bakeVerse(content, refMarker, verse);
    if (newContent !== content) {
      await this.app.vault.modify(file, newContent);
    }
  }
  /**
   * Code block processor for ```bible blocks.
   */
  async codeBlockProcessor(source, el, ctx) {
    const lines = source.trim().split("\n");
    if (lines.length === 0) {
      renderError(el, "Empty bible code block.");
      return;
    }
    const refStr = lines[0].trim();
    const ref = parseReference(refStr);
    if (!ref) {
      renderError(el, `Could not parse reference: "${refStr}"`);
      return;
    }
    const config = {};
    for (let i = 1; i < lines.length; i++) {
      const line = lines[i].trim();
      const colonIdx = line.indexOf(":");
      if (colonIdx > 0) {
        const key = line.substring(0, colonIdx).trim().toLowerCase();
        const value = line.substring(colonIdx + 1).trim();
        config[key] = value;
      }
    }
    if (config["compare"]) {
      const translations = config["compare"].split(",").map((s) => s.trim());
      await this.renderComparisonBlock(el, ref, translations);
      return;
    }
    const translationId = config["translation"] ? this.resolveTranslationId(config["translation"]) : this.settings.defaultTranslation;
    const translationAbbr = config["translation"] ? this.getTranslationAbbr(this.resolveTranslationId(config["translation"])) : this.getTranslationAbbr();
    try {
      const verse = await this.api.getPassage(ref, translationId, translationAbbr);
      renderVerse(el, ref, verse, this.settings.displayStyle, this.settings.preferredWebsite);
    } catch (e) {
      renderError(el, `Failed to fetch ${formatReference(ref)}: ${e.message}`);
    }
  }
  /**
   * Render a comparison block with multiple translations.
   */
  async renderComparisonBlock(el, ref, translations) {
    const verses = [];
    for (const trans of translations) {
      const id = this.resolveTranslationId(trans);
      const abbr = this.getTranslationAbbr(id);
      try {
        const verse = await this.api.getPassage(ref, id, abbr);
        verses.push(verse);
      } catch (e) {
        console.error(`Bible Verse: Failed to fetch ${trans}`, e);
      }
    }
    if (verses.length > 0) {
      renderComparison(el, ref, verses, this.settings.preferredWebsite);
    } else {
      renderError(el, "Failed to fetch any translations for comparison.");
    }
  }
  /**
   * Resolve a translation abbreviation to a HelloAO translation ID.
   * Searches the curated list by abbreviation, then by ID directly.
   */
  resolveTranslationId(abbr) {
    const upper = abbr.toUpperCase();
    const match = HELLOAO_TRANSLATIONS.find(
      (t) => t.abbreviation.toUpperCase() === upper
    );
    if (match)
      return match.id;
    const byId = HELLOAO_TRANSLATIONS.find(
      (t) => t.id.toUpperCase() === upper
    );
    if (byId)
      return byId.id;
    return abbr;
  }
};
